### PR TITLE
Bug 1197444: Fix display of images locally

### PR DESCRIPTION
**Pull request by openjck**
Testing this pull request:

1. `rm -rf static/img`
2. Verify that images *do not* appear
3. `vagrant provison`
4. Verify that images *do* appear

### CODE REVIEW

**Comment by openjck** [comment]
A dual review with @stephaniehobson and @groovecoder would be great! Instructions are in the PR description.

**Comment by openjck** [comment]
This needs to be rebased even though there is no merge conflict. Luke added some documentation in #3507 that this needs to integrate with.

**Comment by darkwing** [comment]
This is working as intended for me; any reason for Stephanie and Luke needing to do this?

**Comment by openjck** [comment]
Verification from @stephaniehobson would be great since she was having this issue in Madison.

**Comment by stephaniehobson** [comment]
Yeah but we fixed my problem in Madison so I don't have the test environment for it anymore. Not sure I can provide a better review than @darkwing.

**Comment by openjck** [comment]
The first step in the guidelines (`rm -rf static/img`) should revert the fix and cause the images not to appear again.

**Comment by openjck** [comment]
Sorry, I wasn't thinking clearly earlier. Since the steps include manually breaking images, anyone can review it.

**Comment by openjck** [comment]
This is all set! :smile:

**Comment by jwhitlock** [comment]
+r.  The steps to reproduce the issue worked, and I was able to follow the directions to switch to serving static from apache2.

**Pull request merged**
