### PR TITLE
updating scss for .prevnext to restrict prevnext menu line width

### PR DESCRIPTION
**Pull request by chrisdavidmills**
As discussed with Stephanie.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@stephaniehobson

**Comment by stephaniehobson** [comment]
@chrisdavidmills You managed to bundle the kumascript submodule into this PR, you'll have to extract it :/

**Comment by chrisdavidmills** [comment]
Dammnit, I managed to do this last time I made a Kuma update too. How do I make sure I don't do this?

**Comment by stephaniehobson** [comment]
The only way I've found is to avoid `git add *`. Since I'm always working on styles `git add kuma/*` works for me.

It's also possible to update the kumascript modules by doing `git submodule update`, but that doesn't always get me out of trouble, which is why I've been more careful about adding files intentionally.

**Comment by chrisdavidmills** [comment]
Ah, that makes sense. I've become too used to just using git add * all the time. right, I'll close this request and try to fix this with a new one.

**Pull request closed without merging**
