### PR TITLE
bug 1184662 - Update profile-related selectors to match current site, make Persona login more reliable

### PR DESCRIPTION
**Pull request by darkwing**
-  A few auth tests fail because we've updated CSS classnames - fixed
-  Updated spelling error :/
-  Using `findByCssSelector`for consistency

### CODE REVIEW

**Comment by groovecoder** [comment]
Can you update the bug # in the commit messages to [bug 1184662](https://bugzilla.mozilla.org/show_bug.cgi?id=1184662)? So the commit comments here trickle up to everyone watching [the staging reliability bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1182182).

**Comment by darkwing** [comment]
Filed this, we'll see what comes of it:  https://github.com/theintern/leadfoot/issues/46

**Comment by darkwing** [comment]
To Do:
- [ ] Make the "auth" / login better in Chrome
- [ ] Fix bug number

**Comment by darkwing** [comment]
Worth a look now :)

**Comment by darkwing** [comment]
I should forewarn there's a likelihood these don't all pass right away.  Please:

1.  Copy failures into a gist and provide them here.
2.  Run tests multiple times -- to see if one test is flaky or legitly failing

**Comment by darkwing** [comment]
Just added an update which re-matches a selector we'd changed.  Just ran tests, all passing Firefox and Chrome for me \o/

**Comment by groovecoder** [comment]
```
× firefox 40.0 on MAC - header - The header search box expands and contracts correctly

intern-local
Tunnel: Ready

Total: [✓✓✓✓✓✓✓✓✓✓✓✓✓✓×✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 31/31
Passed: 30  Failed: 1   Skipped: 0

Fx 40 MAC:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓×✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 31/31, 1 fail
```
Got this twice in a row.

**Comment by darkwing** [comment]
Thanks for the heads up @groovecoder .  I saw that very rarely but part of it could be the border-radius on the search box so I set a mouse offset of 5x5.  Additionally I added additional chai comments to see what isn't adding up (with measurements)

**Comment by groovecoder** [comment]
I updated but got the same failure. :cry:

**Comment by darkwing** [comment]
Did you receive a timeout (didn't get clicked properly) or one of my new failure comments?

**Comment by groovecoder** [comment]
Oh, is this the new failure comment above the summary output?
```
! timed out for isDisplayed: [object Arguments]

intern-local
Tunnel: Ready

Total: [✓✓✓✓✓✓✓✓✓✓✓✓×✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓- ] 29/31
Passed: 28  Failed: 1   Skipped: 0

Fx 40 MAC:  [✓✓✓✓✓✓✓✓✓✓✓✓×✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓- ] 29/31, 1 fail
```
It wasn't red like the big traceback, so I over-looked it.

This was the full trace-back:
```
× firefox 40.0 on MAC - header - The header search box expands and contracts correctly
ScriptTimeout: [POST http://127.0.0.1:4444/wd/hub/session/57c08efe-4787-4d9d-8739-b31c5f3029d7/execute_async / {"script":"return (function (done) {\n                    \n                    \n                    var element = document.getElementById('main-q');\n                    \n                    var eventType = 'transitionend';\n                    \n                    var ev = element.addEventListener(eventType, function () {\n                            \n                            \n                            element.removeEventListener(eventType, ev);\n                            \n                            done();\n                        });\n                }).apply(this, arguments);","args":[]}] Timed out waiting for async script result after 22002ms
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'lcrouch.local', ip: '10.0.1.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.8.0_40'
Driver info: driver.version: unknown
  at Server._post  <node_modules/intern/node_modules/leadfoot/Server.js:68:9>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:57:30>
  at ProxiedSession.Session.executeAsync  <node_modules/intern/node_modules/leadfoot/Session.js:616:15>
  at CompatCommand.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:617:19>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:235:37>
  at runCallbacks  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:11:18>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:188:17>
  at run  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:131:29>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/nextTick.js:30:13>
  at process._tickCallback  <node.js:355:11>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at <CompatCommand.target.(anonymous function) [as executeAsync] (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/Command.js:592:11)>
  at CompatCommand.transitionEndCallback  </Users/lcrouch/code/kuma/tests/ui/tests/header.js:58:30>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:526:11>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:235:37>
  at runCallbacks  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:11:18>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:188:17>
  at run  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:131:29>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/nextTick.js:30:13>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:88:42>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.end  <node_modules/intern/node_modules/leadfoot/Command.js:475:10>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:88:70>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.find  <node_modules/intern/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16)>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:88:76>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at <CompatCommand.target.(anonymous function) (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.getSize  <node_modules/intern/node_modules/leadfoot/compat.js:60:73>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:88:113>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  </Users/lcrouch/code/kuma/tests/ui/tests/header.js:81:29>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.end  <node_modules/intern/node_modules/leadfoot/Command.js:475:10>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:16>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.find  <node_modules/intern/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16)>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:22>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at <CompatCommand.target.(anonymous function) [as moveMouseTo] (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/Command.js:592:11)>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:63>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at <CompatCommand.target.(anonymous function) (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.methods.click  <node_modules/intern/node_modules/leadfoot/compat.js:345:34>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:81>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.end  <node_modules/intern/node_modules/leadfoot/Command.js:475:10>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:89>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:95>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.find  <node_modules/intern/node_modules/leadfoot/Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16)>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:123>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at <CompatCommand.target.(anonymous function) (/Users/lcrouch/code/kuma/tests/ui/node_modules/intern/node_modules/leadfoot/Command.js:656:11)>
  at CompatCommand.getSize  <node_modules/intern/node_modules/leadfoot/compat.js:60:73>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  <tests/header.js:92:160>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>
  at Test.registerSuite.The header search box expands and contracts correctly [as test]  </Users/lcrouch/code/kuma/tests/ui/tests/header.js:92:29>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at signalWaiting  <node_modules/intern/node_modules/dojo/Deferred.js:28:4>
  at resolve  <node_modules/intern/node_modules/dojo/Deferred.js:192:5>
  at runNextSuite  <node_modules/intern/lib/Suite.js:201:50>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
```

**Comment by darkwing** [comment]
So the click still isn't hitting .... OK.  I'll have another look (This passes every time for me... :/)

**Comment by groovecoder** [comment]
I also get more flaky results when I run 2 browsers at a time, at least against the stage server. (Which is mostly what I'm testing since we want to run this after stage deployments.) More time-outs and such.

**Comment by darkwing** [comment]
I noticed the concurrent browser test failure stuff too.  But that's not a test-based issue so we'll just focus on test for now, then work out the the concurrency issue later.

**Comment by darkwing** [comment]
I need to ask a few weird questions:

1.  Does the test pass if you use the `t=header` command line arg?
2.  Does the test pass in Chrome?
3.  Are you keeping the browser "up" when the tests run, or are you kicking off tests and then doing something else?

Sorry for the questions but it will help me.  I could programmatically call `focus()` on the search box to make sure it registers, but the click event is important IMO.

**Comment by darkwing** [comment]
@groovecoder I think I figured it out -- it's hanging on the home search dropdown thingy widget we haven't launched.  Please try again.

**Comment by darkwing** [comment]
Holla!  I rewrote the search box expansions test, now it much more reliably passes!  @groovecoder

**Comment by groovecoder** [comment]
Used this again today during a stage deploy and it was much more reliable in Chrome than last time. I ran Firefox and Chrome at separate times instead of running them simultaneously. But I still got:
```
× firefox 40.0 on MAC - header - The header search box expands and contracts correctly
```
and:
```
× chrome 45.0.2454.15 on MAC - wiki - [requires-login][requires-doc] Clicking the "translate button" allows for translation and CKEditor loads
× chrome 45.0.2454.15 on MAC - wiki - [requires-login][requires-doc] Clicking the edit button goes to edit page, CKEditor loads properly
```

**Comment by darkwing** [comment]
Please try again!

**Comment by groovecoder** [comment]
This worked really well for me for today's stage & prod pushes. Only the firefox search box error now. Which, do we need to keep?

**Comment by groovecoder** [comment]
Kicking to @darkwing for final refactor of search box test or merge - whichever he wants to do.

**Comment by groovecoder** [comment]
I push the button.

**Pull request merged**
