### PR TITLE
Fix Bug 1032455: Remove Helpfulness waffle flag.

### PR DESCRIPTION
**Pull request by stephaniehobson**

### CODE REVIEW

**Comment by groovecoder** [comment]
Is/was there an existing bug? STR:

1. Go to an article page
2. Wait for helpfulness widget pop-up
3. Don't interact with helpfulness widget at all
4. Reload page
5. Don't see helpfulness widget

The widget seems to set helpfulnessTracker and #answered-helpful localStorage key-values immediately? Is it supposed to wait until the user clicks on something?

**Comment by groovecoder** [comment]
If that's expected behavior, r+

**Comment by stephaniehobson** [comment]
That's expected behaviour, I'm trying to keep it as out-of-your-face as possible.

**Comment by groovecoder** [comment]
Needs small rebase after merge of https://github.com/mozilla/kuma/pull/3686 ... the wiki js bundle is probably the conflict.

**Comment by stephaniehobson** [comment]
Updated.

**Pull request merged**
