### PR TITLE
Bug 1197444: Move JavaScript to kuma/static/js

### PR DESCRIPTION
**Pull request by openjck**
Some general testing guidelines:

* Verify that JavaScript URLs still resolve
* Verify that the site still behaves as expected
* Verify that Intern tests still pass

### CODE REVIEW

**Comment by openjck** [comment]
@darkwing @groovecoder

**Comment by darkwing** [comment]
Merge conflict :/

**Comment by openjck** [comment]
Updated!

**Comment by openjck** [comment]
If we could get this in before other major JavaScript changes that would be super-duper. :smile:

**Comment by openjck** [comment]
Added some testing suggestions in the description above.

**Comment by darkwing** [comment]
I'm seeing a really weird git error when I try to pull your branch:

```
From https://github.com/openjck/kuma
 * branch            bug-1197444-staticfiles-js -> FETCH_HEAD
Removing media/js/libs/jquery.scrollTo-1.4.2-min.js
CONFLICT (directory/file): There is a directory with name media/js in HEAD. Adding media/js as media/js~c5a307c2617b3c2918de668f5f8e8bfb1372cf1b
Auto-merging kuma/static/js/wiki.js
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by darkwing** [comment]
Ooops, didn't mean to close this.

**Comment by groovecoder** [comment]
@darkwing - I had no issue checking out the branch. Did you do something with the jquery scrollTo plugin on one of your other branches or something?

I'm checking this out now ...

**Comment by openjck** [comment]
Hm, I can't reproduce this. My guess is that either you had local modifications in *media/js* before switching to this branch or you had a commit from early last week as a parent before switching to this branch.

Try this:

1. git checkout master
2. git pull mozilla master
3. git [however you pull my branch]

**Comment by groovecoder** [comment]
All these resources were requested from `/media/` urls:
```
https://developer-local.allizom.org/media/js/libs/jquery-2.1.0.js?build=1442863961
https://developer-local.allizom.org/media/js/components.js?build=1442863960
https://developer-local.allizom.org/media/js/analytics.js?build=1442863960
https://developer-local.allizom.org/media/js/main.js?build=1442863961
https://developer-local.allizom.org/media/js/auth.js?build=1442863960
https://developer-local.allizom.org/media/js/libs/fontfaceobserver/fontfaceobserver-standalone.js?build=1442863961
https://developer-local.allizom.org/media/js/fonts.js?build=1442863960
```
They are all redirects to `/static/` equivalents, so everything still works.

But it seems `jingo-minify` `js()` helper is going to draw `/media/` urls unless/until we update `JINGO_MINIFY_USE_STATIC = True`? But we would have to do that for both JS and CSS at the same time?

**Comment by openjck** [comment]
We discussed more in IRC.

This pull request needs to update the `{{ js('some-bundle-name') }}` template tags as well. We can tell jingo-minify to use staticfiles to search for JavaScript when building packages, but then jingo-minify would also use staticfiles to search for compiled CSS (which still lives in *media/*). I'll probably need to move stylesheets, at least compiled stylesheets, to *kuma/static* in this pull request as well.

**Comment by groovecoder** [comment]
Should we close this for now until the (minimal) CSS update has been included?

**Comment by openjck** [comment]
I'll shoot for getting the CSS update in today. I'd like to keep it open so that we keep it at top-of-mind.

**Comment by openjck** [comment]
Closed in favor of #3511

**Pull request closed without merging**
