### PR TITLE
bug 1194461 - Change tabzilla images to data URIs

### PR DESCRIPTION
**Pull request by darkwing**
Hardcoding an image used on every page eliminates a request from every page!

### CODE REVIEW

**Comment by groovecoder** [comment]
If we do this and it's the only place we reference those images, we should remove them from the code-base too.

**Comment by darkwing** [comment]
Don't agree with that, tbh, but I'm just getting started; I may make stylus do something fancy with this.

**Comment by groovecoder** [comment]
Sorry, yeah, that should have been a question/suggestion. :smile:

**Comment by darkwing** [comment]
We should wait on this, actually:  https://github.com/mozilla/kuma/pull/3397

**Comment by darkwing** [comment]
Closing, more coming after the PR 3397

**Pull request closed without merging**
