### PR TITLE
Fix bug 1139490: Switch to django-pipeline

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by openjck** [comment]
cc @darkwing @stephaniehobson

**Comment by darkwing** [comment]
I'm seeing removal of `async=True` but does pipeline have no equivalent?

**Comment by openjck** [comment]
> I'm seeing removal of async=True but does pipeline have no equivalent?

In django-pipeline, this needs to be set in *settings.py* ([example](https://github.com/mozilla/kuma/blob/4c714396c4d0becc8fb49f4ed1486054652b80ff/settings.py#L784))

**Comment by darkwing** [comment]
@openjck OK awesome, thanks!  I was browsing the files view, didn't show up there.

**Comment by openjck** [comment]
> @openjck OK awesome, thanks! I was browsing the files view, didn't show up there.

Yeah. The diff was huge because I removed an unused *jquery-ui* directory to get *collectstatic* to pass, but I've updated the commit to keep that directory (minus a couple of files) so that the diff isn't as big.

**Comment by jwhitlock** [comment]
Adding this to requirements/travis.txt might fix the failing tests:

```
Pillow==2.9.0
```

**Comment by jwhitlock** [comment]
I'm getting this error on ```./manage.py collectstatic``:

```
Post-processed 'js/libs/jquery-ui-1.10.3.custom/development-bundle/themes/base/jquery-ui.css' as 'js/libs/jquery-ui-1.10.3.custom/development-bundle/themes/base/jquery-ui.9dd58c18b3fe.css'
Post-processing 'js/libs/jquery-ui-1.10.3.custom/development-bundle/themes/base/jquery.ui.all.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 47, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/src/vendor/src/django/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/src/vendor/src/django/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/src/vendor/src/django/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/src/vendor/src/django/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/src/vendor/src/django/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/vagrant/src/vendor/src/django/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle_noargs
    collected = self.collect()
  File "/home/vagrant/src/vendor/src/django/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
ValueError: The file 'js/libs/jquery-ui-1.10.3.custom/development-bundle/themes/base/jquery.ui.base.css' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f041fb30550>.
```
Is this related to undeleting the ``jquery-ui`` directory?

**Comment by openjck** [comment]
> I'm getting this error on `./manage.py collectstatic:

Good catch. Fixed!

We could remove the entire *js/libs/jquery-ui-1.10.3.custom/development-bundle* directory and other non-essential files from libraries, but that would make the diff unreadable. I'll do that in the future, probably in combination with [bower-installer](https://www.npmjs.com/package/bower-installer).

**Comment by openjck** [comment]
Closing in favor of #3574

**Pull request closed without merging**
