### PR TITLE
bug 1423738: Add 429 "Too Many Requests" response

### PR DESCRIPTION
**Pull request by jwhitlock**
Return a ``429 TOO MANY REQUESTS`` and custom error page when the rate limit is exceeded.

You can view the rate limit page by adding this to a view, such as ``kuma.landing.views.home``:

```
from ratelimit.exceptions import Ratelimited; raise Ratelimited()
```

It looks a lot like the 403 page:

429-tumbeast

### CODE REVIEW

**Comment by jwhitlock** [comment]
I am surprised to learn that the ``IPBan`` only applies to editing.  I'll stop using it for misbehaving scrapers, and rely on @metadave's IP ban tools instead.

I'm going to re-write this bit so that a 403 rather than a 429 is raised for IP bans, in a new commit.

**Comment by safwanrahman** [comment]
I think we can include the `Retry-After` header also

**Comment by jwhitlock** [comment]
I don't think we have enough information for an accurate ``Retry-After`` header, but I guess a hard-coded 60 seconds wouldn't hurt.

**Comment by jwhitlock** [comment]
Lots of stuff:

* Rebased on master
* Added ``Retry-After: 60`` header
* Refactored ``IPBan`` view tests
* Rewrote ``IPBan`` logic as a new decorator ``ban_blocked_ips``, and removed it from the rate limiting decorator.
* Rewrote ``IPBan`` job to cache a list of banned IPs rather than a cache item for each banned IP. I suspect that editing is too rare to justify any caching, but I'm following the lead of past developers.

**Pull request merged**
