### PR TITLE
Bug 962617 - Remove cronjobs

### PR DESCRIPTION
**Pull request by jezdez**

### CODE REVIEW

**Comment by robhudson** [comment]
How does a migration removal work to remove the unused kpi app tables?

**Comment by jezdez** [comment]
@robhudson Deleting the kpi app won't work with a migration since there is obviously not an app to store the migrations. I'll just delete the tables manually :)

**Comment by robhudson** [comment]
> Deleting the kpi app won't work with a migration since there is obviously not an app to store the migrations. I'll just delete the tables manually :)

Ok. I wasn't sure if there was an app that was sort of a global app that you put these into. We're going to be moving towards Django's native migrations in 1.7 in the near distant future and I'm not very familiar with it as we've always used "schematic".

**Comment by robhudson** [comment]
This looks good to me but where are the crontab changes? I.e. where is the removal of the `./manage.py cron` calls and where are the additions of the celery crons defined? I imagined something saying "Run this task at 11am daily" or something similar.

**Comment by jezdez** [comment]
The crontab is maintained outside of the repo and :cyliang is going to help me with this. The ticket has the cronjobs we need to remove.

**Comment by jezdez** [comment]
@robhudson Is this a r+?

**Pull request merged**
