### PR TITLE
fix bug 886016 - Add pagination to the top and bottom of list pages

### PR DESCRIPTION
**Pull request by darkwing**
Easy enough.  The double-bottom-spacing I created is eye-pleasing but I didn't use any science.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
I have some science to confirm your double-bottom-spacing :)

Before David:
screen shot 2015-03-27 at 10 20 50

After David:
screen shot 2015-03-27 at 10 20 50

It IS more pleasing! And I'd like to suggest we drop it to 2em or 30px.

Because the internal elements are floated the changes to the padding is actually helping the element take up the appropriate amount of vertical space. Yay! I think we should change it to 2em to make the padding reflect the actual vertical space without adding any extra to the bottom. 

I suggest ems because the vertical space will change if the text size does. We can go with 30px if you'd rather stick to px though, it gets a little out of vertical alignment with bigger text but nothing breaks.

**Comment by stephaniehobson** [comment]
Silly Github, that's the same image twice.

**Comment by stephaniehobson** [comment]
After David:

screen shot 2015-03-27 at 10 20 13

**Comment by darkwing** [comment]
Updated with `1.5`; sticking with px because it's more consistent with all other spacing!

**Comment by stephaniehobson** [comment]
:+1:

**Pull request merged**
