### PR TITLE
Bug 1206309: Add Edge and Blackberry icons, display tweaks

### PR DESCRIPTION
**Pull request by stephaniehobson**
Also fixed display for IE and Safari mobile.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Wait for #3511

**Comment by darkwing** [comment]
I think we should add the woff2 while we're at it.

**Comment by stephaniehobson** [comment]
Added woff2.

**Comment by stephaniehobson** [comment]
Rebased.

**Comment by darkwing** [comment]
Will pick this up next week when https://github.com/mozilla/kuma/pull/3530 is in.

**Comment by darkwing** [comment]
- With this PR I'm not seeing desktop icons anymore
-  Is there a macro update to see/use the Edge & Blackberry icons?

**Comment by stephaniehobson** [comment]
John made an update to the API which broke some stuff in the kumascript so it needs to be updated. I'll close this until I update the macro.

**Pull request closed without merging**
