### PR TITLE
Fixes #5688, remove fancyTOC.scss from new frontend

### LINKED ISSUE #5688: Remove fancyTOC from new front-end
We can safely remove @import '../components/wiki/content/fancyTOC'; from the new front-end as it is not being used.

## Potential savings

```
+--------------------------------------------------------------+
| Size         | 831 bytes                                     |
|--------------------------------------------------------------|
| Gzipped      | 380 bytes                                     |
|--------------------------------------------------------------|
```

### PR DESCRIPTION
**Pull request by schalkneethling**
Removes the `fancyTOC.scss` import from the new frontend. I also removed `wiki-shared.scss` as that is no longer used.

@peterbe r?

### CODE REVIEW

**Comment by peterbe** [comment]
@schalkneethling Can you fix the conflict?

**Comment by schalkneethling** [comment]
> @schalkneethling Can you fix the conflict?

Resolved.

**Comment by peterbe** [comment]
Wanna merge it now?

**Comment by schalkneethling** [comment]
> Wanna merge it now?

I reckon it should be safe to merge now.

**Pull request merged**
