### PR TITLE
Bug 975868 - Update CKEditor to 4.4.8

### PR DESCRIPTION
**Pull request by darkwing**
Includes a XSS security update as detailed in the changelog.

### CODE REVIEW

**Comment by darkwing** [comment]
Marking as DO NOT MERGE due to `master` merge moratorium.

**Comment by darkwing** [comment]
http://dictionary.reference.com/browse/alliteration

**Comment by groovecoder** [comment]
Test failure may be legit?

**Comment by darkwing** [comment]
Not sure what that has to do with CKEditor. Kicking, will see what happens.  Also, we need to redo this based on previous branch :/

**Comment by darkwing** [comment]
Closing based on talking with @jezdez

**Pull request closed without merging**
