### PR TITLE
Intern stability 1152386

### PR DESCRIPTION
**Pull request by darkwing**
Simply PR'ing this so WebQA can look.

### CODE REVIEW

**Comment by darkwing** [comment]
This is ready for a look.  This makes login more reliable and also adds destructive tests to the wiki.

Run as follows to test:

./node_modules/intern/bin/intern-runner.js config=intern-local.js b=firefox u=yourwikiuser@domain.com p=YourPass d=developer-local.allizom.org destructive=true t=wiki

**Comment by groovecoder** [comment]
Kicked Travis job.

**Comment by openjck** [comment]
Travis looks good now. Testing...

**Comment by openjck** [comment]
Looks good aside from one thing. The destructive tests assume the existence of `docs/Web`, but we've also talked about not running these tests on production. Can we instead create a page so that the tests don't have a working database import as a dependency?

**Comment by darkwing** [comment]
>> I was unable to run the destructive tests because they assume the existence of docs/Web

It doesn't at all.  The destructive tests create a page at `test_2938743924` or whatever the timestamp is.  `docs/Web` doesn't come into play at all.

**Comment by openjck** [comment]
Something else must have went wrong, then. Could have sworn I saw `docs/Web` show up in the log output. I'll look again.

**Comment by groovecoder** [comment]
Been using these to test the django update on stage. I think http://kuma.readthedocs.org/en/latest/tests-ui.html needs an update with better display of all the test options.

**Pull request merged**
