### PR TITLE
bug 1291892 - Clear session on Persona signup fail

### PR DESCRIPTION
**Pull request by jwhitlock**
When signup fails (due to registration being closed, or an attempt to signup with Persona), clear the social login from the session, so that it doesn't later interpret a new social login as an attempt to link accounts.

Here's the tests I did locally:

**Test 1**: Verify [bug 1063830](https://bugzilla.mozilla.org/show_bug.cgi?id=1063830) is still fixed:

1. Create an account associated with Persona and Github, both of which share an email.
2. Disconnect the GitHub account, log out
3. Login with the GitHub account, get a banner that "A profile already exists with an email address below."
4. Click the link in the banner to start a Persona login.
5. Sign in with a new, different Persona account, get message "Could not find profile matching that account." (fix for bug 1063830)
6. Sign in with the Persona account with the matching email, get to the Account Connections screen with the GitHub and Persona accounts associated.

**Test 2**: Verify [bug 1291892](https://bugzilla.mozilla.org/show_bug.cgi?id=1291892) is fixed:

First, clear out connection data by running ``./manage.py shell_plus``, and these commands:

```
Session.objects.all().delete()
SocialAccount.objects.all().delete()
me = User.objects.get(username='jwhitlock')  # Replace with your username
me.username = 'jwhitlock_old'  # Or another unique username
me.save()
(Ctrl-D to quit)
```

Reload the local MDN page, and confirm you are signed out.  Now:

1. Sign in with the Persona account. Get a "signup with Persona not allowed" message.
2. Click the link to "try again with a GitHub account". Sign in with Github. You are allowed to create an account.
3. Complete profile creation. If you have multiple GitHub emails, pick the one that matches the Persona email. Accept terms. "Create my MDN Profile".
4. Click the username in the header section to open the Profile page, then Edit to edit it. Select "Use your Persona account to sign in."
5. Pick the email that matches the GitHub / MDN profile email, Sign In. Get to the profile editing page with the GitHub and Persona accounts associated.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
I... did not follow your steps and something weird happened.

1) disassociated GitHub
2) signed out
3) signed in with *Persona*, new email address never used before
4) got "create your MDN profile to continue" page with "Could not find profile matching that account." error message and "A profile already exists with an email address below." message and "Your GitHub username stephaniehobson is already taken" message. 0.0

Going to follow the steps properly now, BRB.

**Comment by stephaniehobson** [comment]
Also getting "Could not find profile matching that account" error when trying to associate a new Persona with an existing account :/

**Comment by stephaniehobson** [comment]
Test1 is good. Test2 results in "Could not find profile matching that account." error :(

**Comment by jwhitlock** [comment]
I got the same error.  Here's what I did:

1. Ran Test 1. This can all be done from the website (disconnect GitHub, log in)
2. Ran ``./manage.py shell_plus``, then:

```
Session.objects.all().delete()
SocialAccount.objects.all().delete()
me = User.objects.get(username='jwhitlock')
me.username = 'jwhitlock_old')
me.save()
(Ctrl-D to quit)
```

3. Refresh the MDN page
4. Sign in with the Persona account. Get a "you can not create a profile with Persona" message
5. Click the link to sign in with Github. Pick the Persona email, accept the terms, create the profile.
6. Go to the profile page, edit it, select "Use your Persona account to sign in". Pick the Persona email.
7. Get to the account connection page, with "Could not find profile matching that account." error 😢 

Back to the code...

**Comment by jwhitlock** [comment]
Progress! In the steps above:

1. Run Test 1, works.
2. Run the commands to clear sessions, social accounts, free up the Github user name
3. Refresh the MDN page
4. Sign in with the Persona account. Get a "you can not create a profile with Persona" message
5. Click the link to sign in with Github. Pick the Persona email, accept the terms, create the profile.
6. **Log out, and log back in again**
7. Go to the profile page, edit it, select "Use your Persona account to sign in". Pick the Persona email.
8. Back to the profile page, with the Persona account connected 😄 

The issue appears to be if you try to connect a second account after just creating an account.  The session has a value `socialaccount_sociallogin` which represents the social account used. If you just created account, it says you don't have an account yet. If you log out and log in again, `socialaccount_sociallogin` includes that you have an existing account.  Adding some more code...

**Comment by jwhitlock** [comment]
I was wrong, but on the right track.  When you log out and log in again, there is no ``socialaccount_sociallogin`` in the session - it's only used when creating a new profile from a social account.  I've added logic to clean the key out of the session after successfully creating the user.  This allows a user to connect a second social account during their initial session.

**Comment by jwhitlock** [comment]
Also tried [the weird thing](#issuecomment-238351439) and I got the "Persona Disabled" screen as expected.

I've updated the initial instructions to say how to manually clear out the session and social login data, and free up your username for a quick GitHub login. @stephaniehobson, can you try again?

**Comment by stephaniehobson** [comment]
All tests pass :) R+

**Pull request merged**
