### PR TITLE
Bug 1197444: Move stylesheets, JS to kuma/static

### PR DESCRIPTION
**Pull request by openjck**
Setup:

Be sure to do a `vagrant provision` before testing this.

Some general testing guidelines:

* Verify that the site looks and behaves as expected
* Verify that Intern tests pass
* Verify that the above again while emulating production ([instructions](https://kuma.readthedocs.org/en/latest/development.html#production-assets))

Other notes:

In the past, running `./manage.py compress_assets` was enough to enable syntax highlighting. Because minified and non-minified assets are now hosted very differently, we need to fully enter production mode ([instructions](https://kuma.readthedocs.org/en/latest/development.html#production-assets)) to enable syntax highlighting.

Once we switch to django-pipeline, we may be able to get syntax highlighting to work in both environments without any extra work, which would be an improvement even over what we have now.

### CODE REVIEW

**Comment by openjck** [comment]
@groovecoder @darkwing

**Comment by darkwing** [comment]
Merge conflict

**Comment by openjck** [comment]
Updated! :smile:

Rebases on this branch are going to be rough. If possible, it would be great if we could prioritize this over other PRs.

**Comment by openjck** [comment]
At the moment, `./manage.py collectstatic` will need to be run to test this. That won't be needed after #3510 is merged.

**Comment by stephaniehobson** [comment]
Error compiling the stylus files:
```
failed to locate @require file components/doc-title.styl
```
(it was in the old location, probably added after you started working on this)

Not sure if this is related but I get a ISE when attempting to visit any profiles.

Code samples are not getting prismed and the good/bad styles are not being applied either. This page has sample code for testing both: https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code

**Comment by jwhitlock** [comment]
Got an exception on the home page:

* ``vagrant halt; vagrant up; vagrant provision``
* Ensured ``settings-local.py`` was in dev mode (``DEBUG=True``, etc.)
* Ensured apache config was in dev mode (``/etc/apache2/sites-enabled/kuma.conf`` has ``Alias`` lines for static commented out)
* Removed everything under static
* Started the services

I get this traceback on the home page (https://developer-local.allizom.org/en-US/)

```
Traceback (most recent call last):
  File "/home/vagrant/src/vendor/src/django/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/src/vendor/src/django/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/home/vagrant/src/vendor/src/django/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/vagrant/src/vendor/src/django/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/src/vendor/src/django/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/vagrant/src/kuma/landing/views.py", line 31, in home
    return render(request, 'landing/homepage.html', context)
  File "/home/vagrant/src/vendor/src/django/django/shortcuts.py", line 50, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/vagrant/src/vendor/src/django/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/home/vagrant/src/vendor/src/jingo/jingo/__init__.py", line 206, in render
    return super(Template, self).render(context_dict)
  File "/home/vagrant/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vagrant/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/src/kuma/landing/templates/landing/homepage.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/vagrant/src/templates/base.html", line 19, in top-level template code
    {% block site_css %}
  File "/home/vagrant/src/kuma/landing/templates/landing/homepage.html", line 6, in block "site_css"
    {{ super() }}
  File "/home/vagrant/src/templates/base.html", line 20, in block "site_css"
    {{ css('mdn', 'all') }}
  File "/home/vagrant/src/vendor/src/jingo-minify/jingo_minify/helpers.py", line 153, in css
    urls = get_css_urls(bundle, debug)
  File "/home/vagrant/src/vendor/src/jingo-minify/jingo_minify/helpers.py", line 117, in get_css_urls
    item in items]
  File "/home/vagrant/src/vendor/src/jingo-minify/jingo_minify/helpers.py", line 40, in _get_mtime
    return int(os.path.getmtime(get_path(item)))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/home/vagrant/src/static/css/main.css'
```

I got the same issue as @stephaniehobson related to rebuilding main.css, from ``./scripts/compile-stylesheets``:

```

/usr/lib/node_modules/stylus/bin/stylus:646
              throw err;
                    ^
Error: scripts/../kuma/static/stylus/main.styl:17:10
   13| @require 'components/components';
   14| @require 'components/content';
   15| @require 'components/structure';
   16| @require 'components/tags';
   17| @require 'components/doc-title';
----------------^
   18| 

failed to locate @require file components/doc-title.styl

    at Evaluator.visitImport (/usr/lib/node_modules/stylus/lib/visitor/evaluator.js:898:21)
    at Evaluator.Visitor.visit (/usr/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/lib/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.visitRoot (/usr/lib/node_modules/stylus/lib/visitor/evaluator.js:689:27)
    at Evaluator.Visitor.visit (/usr/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/lib/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.evaluate (/usr/lib/node_modules/stylus/lib/visitor/evaluator.js:229:15)
    at Renderer.render (/usr/lib/node_modules/stylus/lib/renderer.js:86:26)
    at /usr/lib/node_modules/stylus/bin/stylus:640:15
    at fs.js:272:14
```

**Comment by openjck** [comment]
Updated. The `compile-stylesheets` error, the `compress_assets` error, the profile ISE, and syntax highlighting have all been corrected. Nice sleuthing!

Code samples can only be tested in production mode. See the pull request description for rationale instructions.

**Comment by jwhitlock** [comment]
Worked in dev mode with empty static folder.  After following instructions, worked in server mode, with syntax highlighting.  Only looked home page and local copy of https://developer.mozilla.org/en-US/docs/User:stephaniehobson:code , which is pretty intense.

Got a CommandError while running ``./manage.py compress_assets``:
```
(env)vagrant@developer-local:~/src$ ./manage.py compress_assets
To turn on cache busting, use settings.CACHEBUST_IMGS
Minifying /home/vagrant/src/static/css/wiki-all.css (using clean-css)
Minifying /home/vagrant/src/static/css/error-404-all.css (using clean-css)
...
Minifying /home/vagrant/src/static/js/wiki-compat-tables-all.js (using UglifyJS)
cat: /home/vagrant/src/static/js/libs/jquery.scrollTo-1.4.2-min.js: No such file or directory
cat /home/vagrant/src/static/js/libs/jquery.hoverIntent.minified.js /home/vagrant/src/static/js/libs/jquery.scrollTo-1.4.2-min.js /home/vagrant/src/static/js/demos.js /home/vagrant/src/static/js/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js /home/vagrant/src/static/js/modal-control.js > /home/vagrant/src/static/js/demostudio-all.js.tmp exited with a non-zero status.
Minifying /home/vagrant/src/static/js/demostudio-all.js (using UglifyJS)
CommandError: one or more minify commands exited with a non-zero status. See output above for errors.
```
The key error appears to be:
```
cat: /home/vagrant/src/static/js/libs/jquery.scrollTo-1.4.2-min.js: No such file or directory
```

**Comment by openjck** [comment]
Nice catch. Updated! :smile:

**Comment by jwhitlock** [comment]
+r works with fixes

**Comment by groovecoder** [comment]
:clap:

**Pull request merged**
