### PR TITLE
Bug 1568305, add specific styling for active state on in content links

### PR DESCRIPTION
**Pull request by schalkneethling**
@callahad This adds a specific style for the active state of in-content

active-style

r?

### CODE REVIEW

**Comment by callahad** [comment]
Looks good, but I noticed that using bold can force other text on the line
to jump / reflow when you click -- maybe just a stronger color change would
be sufficient?

**Comment by schalkneethling** [comment]
> Looks good, but I noticed that using bold can force other text on the line to jump / reflow when you click -- maybe just a stronger color change would be sufficient?

I was thinking that as well originally but, it is tricky to find a color combo that is also accessible for people with color blindness. Our current link color is blue, which is great but, it makes a different color kinda tricky unless we go for something like an orange/yellow.

I am a little wary of that direction because generally those colors indicate a warning, or that something is not quite right.

That is the reason I chose to indicate the interaction not only with color.

**Comment by schalkneethling** [comment]
@callahad Here are two more options to consider:

### Using background-color

background-active

### Using text-deoration-style: double; as you suggested

double-active

**Comment by callahad** [comment]
I really like the background-color one, would r+ :)

**Comment by schalkneethling** [comment]
@callahad updated.

**Pull request merged**
