### PR TITLE
bug 1246967 - Add Document.uuid to database, plus other migrations

### PR DESCRIPTION
**Pull request by jwhitlock**
Update Kuma migrations to match the state of the models. Then add Document.uuid to the database, nullable with a default of null.

This is part 1 of 3 steps to add Document.uuid. Each step needs to be pushed to production, with migrations applied to the database, before the next step is merged.

1. PR #3793 (this PR) - Add empty Document.uuid to database
2. PR #3794 - Populate Document.uuid and use in $json API
3. PR #3795 - Require non-null Document.uuid and refresh $json API

### CODE REVIEW

**Comment by jwhitlock** [comment]
This PR has the same migrations as #3769, will rebase when that is merged.

**Comment by jwhitlock** [comment]
Now that #3769 is merged, rebased on master and removed duplicate migrations.

**Comment by jwhitlock** [comment]
Needs rebase after migrations in PR #3793.

**Comment by jwhitlock** [comment]
Now that PR #3808 is merged, ready for review again.  This migration takes 141 seconds in my development VM, but shouldn't require a hard-hat.

**Comment by jezdez** [comment]
r+

**Pull request merged**
