### PR TITLE
Fix bug 1126386: Upgrade Django to 1.4.19.

### PR DESCRIPTION
**Pull request by ubernostrum**

### CODE REVIEW

**Comment by groovecoder** [comment]
Will this fail Travis unless/until we put the branch on mozilla repo and send PR from there?

**Comment by jezdez** [comment]
No, that's history now that the wheel ball is gone.

**Comment by ubernostrum** [comment]
(it passed)

**Comment by groovecoder** [comment]
Spot-check looks good.

**Pull request merged**
