### PR TITLE
fix bug 1121493 - Prevent CKEditor from overriding link text

### PR DESCRIPTION
**Pull request by darkwing**
Have to commit the entire build, but the fix is here:

https://github.com/mozilla/kuma/compare/mozilla:master...darkwing:1121493-link-text?expand=1#diff-457f733f4579028bdc92e93700e87b73R160

### CODE REVIEW

**Comment by groovecoder** [comment]
Do I need to run a build command or something for this? I tried a force-refresh on the edit page and I still get the old broken behavior. :frowning:

**Comment by darkwing** [comment]
You need to clear your cache.

**Comment by darkwing** [comment]
What I tested was:

1.  Highlight some text, choose link, watch text get linkified and unchanged.
2.  Click link button, choose something without anything highlighted, watch proper title text used.

**Comment by groovecoder** [comment]
I saw the [en-US] still shown in the link dialog's Article Title/Link Text, so I didn't even try to save it.
ckeditor-link-title
When I did save it, it saved the link text correctly. Does yours do that too?

**Comment by darkwing** [comment]
Looking again

**Comment by darkwing** [comment]
I'm seeing this:  http://screencast.com/t/uFwxIq5j , which should be the correct solution.

**Comment by groovecoder** [comment]
I might be reading the bug wrong then. But I'm going to ask there to check on this fix.

**Comment by darkwing** [comment]
OK, updated again to allow for the second request in the ticket.

**Comment by groovecoder** [comment]
This looks good to me now. Does @openjck need to review anything in particular, or can I merge + push?

**Comment by darkwing** [comment]
May be good to have him review since CKE is core to the site.

**Comment by openjck** [comment]
Sounds good. I'll take a look.

**Comment by openjck** [comment]
LGTM :trophy:

**Pull request merged**
