### PR TITLE
Fix bug 1178688 - Added rmpyc helper to bash environment.

### PR DESCRIPTION
**Pull request by jezdez**

### CODE REVIEW

**Comment by groovecoder** [comment]
FWIW, for things like this I tend to re-use bug 957802 instead of filing new bugs for each change we make to streamline the dev vm setups.

**Comment by kleberveridiano** [comment]
NICE JOB!

**Comment by kleberveridiano** [comment]
i LOVE YOU

**Comment by kleberveridiano** [comment]
...World´s keep on turning...

**Comment by kleberveridiano** [comment]
see you soon...

**Pull request merged**
