### PR TITLE
Issue #5685, remove Emotion and move CSS to Sass - titlebar

### PR DESCRIPTION
**Pull request by schalkneethling**
@peterbe r?

### CODE REVIEW

**Comment by Gregoor** [comment]
Some changes I'm seeing on my machine:
`.titlebar-container { background-color` from `blue` to `grey`
`h1 { font-size` from `45.3px` to `51px`
Also the size changes to `25px` (instead of `28px`) on small devices. And the breakpoint for that is now ~tablet, where it is ~phone on the prod beta site.

**Comment by schalkneethling** [comment]
> Some changes I'm seeing on my machine:
> `.titlebar-container { background-color` from `blue` to `grey`
> `h1 { font-size` from `45.3px` to `51px`
> Also the size changes to `25px` (instead of `28px`) on small devices. And the breakpoint for that is now ~tablet, where it is ~phone on the prod beta site.

Thank you for the review @Gregoor - These changes are intentional. One of the downsides of having this decoupled from the Sass codebase was that a lot of values was not using the defined variables we have for font sizes, colors margins, padding, breakpoints etc. It was also not following a mobile-first approach.

You will, therefore, see a number of places in these pull requests where adjustments like these have been made.

**Comment by schalkneethling** [comment]
Also, just a quick note. It will be best if we work through these in the order of the pull requests. I believe #5700 has been merged so, next in line should be #5701, then #5702, etc. Thanks!

**Comment by Gregoor** [comment]
Great, thanks for the elaboration. Then it looks good to me! 🚀

**Pull request merged**
