### PR TITLE
Bug 1414107: Remove line_length waffle

### PR DESCRIPTION
**Pull request by stephaniehobson**
Can be reviewed now but need to wait until next week to get go-ahead. 

(Not actually expecting this will be reviewed until next week ;)

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Confident we can roll this into production now. Once it's signed off of course.

**Comment by jwhitlock** [comment]
Does the ``[DO NOT MERGE]`` in the title still apply?

**Comment by stephaniehobson** [comment]
Oops, no.

**Comment by schalkneethling** [comment]
No reference found to any of the following:

wiki-skinny.scss
main-skinny.scss
includes-skinny
components-skinny
line_length

**Pull request merged**
