### PR TITLE
Bug 1570022, set min width on whoami widget

### PR DESCRIPTION
**Pull request by schalkneethling**
@peterbe r?

### CODE REVIEW

**Comment by peterbe** [comment]
And here's what happens in German:
Screen Shot 2019-08-13 at 10 08 27 AM

**Comment by schalkneethling** [comment]
> And here's what happens in German:
> Screen Shot 2019-08-13 at 10 08 27 AM

Ugh, our layout is soooo brittle at the moment. Let me add some fallbacks and tweaks.

**Comment by schalkneethling** [comment]
@peterbe updated

**Comment by peterbe** [comment]
Hmm.... See https://travis-ci.org/mozilla/kuma/builds/571394145
It's failing on some snapshots I guess.

**Comment by peterbe** [comment]
Much better!
Screen Shot 2019-08-13 at 12 58 12 PM

**Comment by peterbe** [comment]
Not so good
Screen Shot 2019-08-13 at 1 00 06 PM

I guess I got to test properly in Safari on my physical iPhone to really see how it works on iOS.

**Comment by peterbe** [comment]
Looks better on Safari's Responsive Mode tool
Screen Shot 2019-08-13 at 1 02 21 PM

**Comment by schalkneethling** [comment]
@peterbe Yeah, the mobile view is seriously ugly and busted. We decided to leave it as-is for now, however, I am planning on making some improvements as soon as I have completed all the "above the black bar" issues.

Perhaps we can get this one in, and I will then open another PR to at least make the header portion more palatable. Thoughts?

Also, snapshot tests will pass now.

**Pull request merged**
