### PR TITLE
[Bug 1218563] Update ihavepower command to take optional password

### PR DESCRIPTION
**Pull request by safwanrahman**
It now takes a optional password with the management command. @jwhitlock r?

### CODE REVIEW

**Comment by jwhitlock** [comment]
The code looks good. I'm creating and loading an anonymized database to try it out.

**Comment by jwhitlock** [comment]
Fails for me with ```CommandError: User already has the power!```, without settings the password.

**Comment by safwanrahman** [comment]
> Fails for me with CommandError: User already has the power!, without setting the password.

It should fail for you cause you already have superuser access.

**Comment by safwanrahman** [comment]
As per IRC conversation @jbradberry mentioned that, we can use ``./manage.py changepassword <username>`` to create a password

**Comment by safwanrahman** [comment]
@jwhitlock Fixed

**Comment by jwhitlock** [comment]
Thanks @safwanrahman!

**Pull request merged**
