### PR TITLE
bug 957802 - Update node provisioning

### PR DESCRIPTION
**Pull request by jwhitlock**
Update to the latest version of the ansible-galaxy role ``nodesource.node``, and then patch it to install the NodeSource apt GPG key from keyserver.ubuntu.com, since they switch to CloudFront and SNI for the old file server, and the old version of Python in Ubuntu 14.04 can't handle it.

### CODE REVIEW

**Comment by safwanrahman** [comment]
So I have updated ``python`` version in my VM, delete the virtualenvironment and the provisioning worked. I have installed the python from [this ppa](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7)

So in my VM, the ``python -V`` returns ``Python 2.7.12``

So what we can do in our vagrant setup? We can either change the setup so it will install python 2.7.12 or we can change the box to ``ubuntu 16.06`` that have python 2.7.12 by default.

**Comment by safwanrahman** [comment]
I forgot to add, I have also updated ansible in my host machine. downgrading ``ansible`` to 1.9.x replicate the problem

**Comment by safwanrahman** [comment]
So I was investigating the issue for some hours, and it seems that, having ``python 2.7.12`` with ``ansible 2.1.1`` does not raise the problem in my local machine.

But the travis ci made me confuse. It is showing that its using ``python 2.7.12`` but I can not understand which hell build of python 2.7.12 they are using.
I have changed the script to install ``python 2.7.12`` from a PPA, and the [test](https://travis-ci.org/safwanrahman/kuma/jobs/158704861) is working fine in travis! 
This is the [patch](https://github.com/mozilla/kuma/compare/master...safwanrahman:master)

**Comment by jwhitlock** [comment]
After discussion in IRC, changing the ansible rule is the fastest way to work around this problem.

Updating the system Python to 2.7.12 via the PPA works as well, in TravisCI's Ubuntu 12.04 environment, the beta 14.04 environment, and the Vagrant 14.04 environment.  It should be safe to update the system Python to a new minor version, although the official releases avoid it, requiring the PPA route.

Changing the system Python will break user's existing Vagrant environments, requiring manual steps to rebuild the virtual environment.  If we are going that route, it may make sense to update Vagrant to use 16.04, like the new Docker environment, and make people recreate their VMs.

This change has been submitted upstream as https://github.com/nodesource/ansible-nodejs-role/pull/34.  There are a lot of people impacted, so there may be an "accepted" fix in the coming weeks, maybe by switching ansible role providers.

**Pull request merged**
