### PR TITLE
Fix Bug 1420371: Samsung, Firefox, footnote, icon update

### PR DESCRIPTION
**Pull request by stephaniehobson**
- Add Samsung Internet Browser Icon
- Update Firefox icon
- Change footnote icon from `[ ]` to `*`

### CODE REVIEW

**Comment by stephaniehobson** [comment]
@Elchi3 🎁

**Comment by schalkneethling** [comment]
Not sure if I missed a step but, I fetched this branch, updated the sub-modules, started docker, ran build-static, restarted web as well as kumascript, and have gulp running.

With all of the above, the new/changed icons are not showing up:

screen shot 2017-12-21 at 12 16 14

and

screen shot 2017-12-21 at 12 19 07

**Comment by jwhitlock** [comment]
If you are removing ``compat-icons.eot``, etc., you'll need to remove the reference from ``kuma/static/styles/base/fonts/compat-icons.scss`` as well.

**Comment by schalkneethling** [comment]
> If you are removing compat-icons.eot, etc., you'll need to remove the reference ...

Ah yes, that is why there was the message about unliked files from Gulp

**Comment by stephaniehobson** [comment]
Oh no, I put the new files in `/static/` instead of `/kuma/static/`. I hope I still have them...

`/static/` is my nemesis.

**Comment by stephaniehobson** [comment]
I should add, the macro doesn't add Samsung Internet Browser to the table yet, so you'll have to test by changing the class on one of the others with dev tools.

**Comment by stephaniehobson** [comment]
Okay, try it again :)

**Pull request merged**
