### PR TITLE
Fix bug 1279688 – search in all topics for macro usage

### PR DESCRIPTION
**Pull request by Elchi3**
https://bugzilla.mozilla.org/show_bug.cgi?id=1279688 

https://www.youtube.com/watch?v=2ZBtPf7FOoM

### CODE REVIEW

**Comment by SebastianZ** [comment]
As stated in https://bugzilla.mozilla.org/show_bug.cgi?id=1279688#c3, I think that is not the right approach.

Sebastian

**Comment by stephaniehobson** [comment]
👍

**Comment by SebastianZ** [comment]
Ehm, @stephaniehobson, what about [my comment](https://github.com/mozilla/kuma/pull/3887#issuecomment-225494044)?

Sebastian

**Comment by SebastianZ** [comment]
> Ehm, @stephaniehobson, what about [my comment](https://github.com/mozilla/kuma/pull/3887#issuecomment-225494044)?

Just saw your comment on Bugzilla. Sorry for the noise!

Sebastian

**Pull request merged**
