### PR TITLE
bug 1197858 - Upgrade intern to 3.0.3

### PR DESCRIPTION
**Pull request by darkwing**
Upgrades Intern to 3.0.3, removes old demo/homepage test

### CODE REVIEW

**Comment by groovecoder** [comment]
I checked out this branch and ran `npm install Intern@^3.0` and then got:
```
intern-local
Total: Pending
Passed: 0  Failed: 0  Skipped: 0
```
Did I miss a step?

**Comment by groovecoder** [comment]
Oops, I ran the install outside of the `tests/ui` directory. Running now ...

**Comment by groovecoder** [comment]
```
Chr 47 MAC: [✓×✓×✓✓✓✓✓✓✓×✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 31/31, 3 fail
```

**Comment by groovecoder** [comment]
```
× chrome on any platform - header - The header search box expands and contracts correctly
× chrome on any platform - demos - The 3 featured "demos-main" element is present
× chrome on any platform - home - Hacks posts display properly
```

**Comment by darkwing** [comment]
Updated to isolate testing, including axing multiple concurrency to ensure tests run properly.

**Comment by groovecoder** [comment]
This just worked for me to test our latest deployment to stage via BrowserStack. :clap:

**Pull request merged**
