### PR TITLE
Bug 1125850 - Catch StaleDocumentsRenderingInProgress exception at the right place.

### PR DESCRIPTION
**Pull request by jezdez**

### CODE REVIEW

**Comment by robhudson** [comment]
rebase

**Comment by robhudson** [comment]
Is this the cause for some of the task failures I see in the admin?

**Comment by jezdez** [comment]
@robhudson Yeah, it was just an oversight that the exception wasn't moved with the task

**Comment by robhudson** [comment]
Cool, Gonna merge it.

**Pull request merged**
