### PR TITLE
Bug 1123748 - Home CTA update

### PR DESCRIPTION
**Pull request by stephaniehobson**
Updated calls to action.

Changed background position technique to use absolutely positioned generated elements so the background could be placed more precisely in RTL.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Needs to be merged before PR #3170.

**Comment by stephaniehobson** [comment]
Having problems with the colour management settings of the sprite on retina displays. Hold of on review.

**Comment by stephaniehobson** [comment]
Okay, I think I fixed it.

**Comment by darkwing** [comment]
Love it!

**Pull request merged**
