### PR TITLE
Fix bugs 1110230 and 1082031 - Updated Celery to 3.x including its dependencies.

### PR DESCRIPTION
**Pull request by jezdez**
This also updates a bunch of dependencies:

- billiard to 3.3.0.19
- celery to 3.1.17
- django-celery to 3.1.16
- kombu to 3.0.24
- librabbitmq to 1.6.1

We also remove the previously overridden South migrations for django-celery
and start to store task results in the database instead of RabbitMQ to
prepare for the eventual move to Redis as the broker and the ability to see
task results online.

Update timezone information (pytz).

### CODE REVIEW

**Comment by groovecoder** [comment]
Sorry to be the fun police again, can we re-word today's commit messages to be prefixed with the bug #?

**Comment by jezdez** [comment]
@groovecoder So we have the compiled things and the celerycam in place on stage and I'm going to do a stage deploy tomorrow to check all the celery related things out before doing the prod deploy on Monday.

**Comment by groovecoder** [comment]
@jezdez sounds good. Thanks for sticking to this.

**Comment by groovecoder** [comment]
FWIW, I gave the final r+ on this for merge & push.

**Pull request merged**
