### PR TITLE
Bug 1150118 - Lazy load fonts

### PR DESCRIPTION
**Pull request by stephaniehobson**
Some clean up in anticipation of changes to font stuff:

- Use variable to set font family
- Use mixin to set font size
- Added Arial to fallback list (more size appropriate than Helvetia which is Mac sans-serif default)
- Line-height and letter-spacing should be relative to font-size not pixels

### CODE REVIEW

**Comment by darkwing** [comment]
I see what you're doing but is there something I should be looking for in testing?

**Comment by stephaniehobson** [comment]
Nothing specifically. If I did everything right there should no be visible changes anywhere.

**Comment by darkwing** [comment]
Hey @stephaniehobson, I'm seeing a noticeable difference:

http://screencast.com/t/7hLTcxAMuas  - Master

http://screencast.com/t/fxIDRPXFmmn  - Stephanie's branch

If you overlay those two images, your fonts appear different.

**Comment by stephaniehobson** [comment]
Okay, weird. I have some work to do.

**Comment by stephaniehobson** [comment]
Blergh. Made a stupid mistake. Thank goodness for code reviews. Should be better now.

**Comment by darkwing** [comment]
Looks good! :)

**Pull request merged**
