### PR TITLE
Bug 1218563 - Add new Docker config based on kuma_base

### PR DESCRIPTION
**Pull request by jwhitlock**
Rebase and squash of PR #3852, now in mozilla/kuma repo for collaboration.

### CODE REVIEW

**Comment by jwhitlock** [comment]
This is looking good, tests pass in TravisCI, no changes needed to Vagrant or deployment environments.

@jgmize: is there more that you want to do on this PR, or merge what we have so far and address next steps in follow-up PRs?

**Comment by jwhitlock** [comment]
This is looking good, tests pass in TravisCI, no changes needed to Vagrant or deployment environments.

@jgmize: is there more that you want to do on this PR, or merge what we have so far and address next steps in follow-up PRs?

**Comment by jwhitlock** [comment]
This is looking good, tests pass in TravisCI, no changes needed to Vagrant or deployment environments.

@jgmize: is there more that you want to do on this PR, or merge what we have so far and address next steps in follow-up PRs?

**Comment by jgmize** [comment]
Yes, I think merging what we have so far into master makes sense at this point. Thanks @jwhitlock

**Pull request merged**
