### PR TITLE
Fix bug 1233188 - Removed helpfulness database models and code

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by jezdez** [comment]
Yikes, just realized that this is pretty old code, 6f26978456b32edb7383176e32b9aa7af1327ce4

**Comment by jezdez** [comment]
some references to the `wiki_helpfulvote` tables linger
[ ] `scripts/anonymize.sql`
[ ] `scripts/clone_db.py`

**Comment by jezdez** [comment]
Depending on whether you're going to merge #3714 first or not, this may need a renaming of the migration.

**Comment by jezdez** [comment]
r+wc

**Comment by robhudson** [comment]
I was very confused for awhile thinking these models were used with the new helpfulness.js work.

Yep, I did notice there was a migration number conflict. I'll fix that before merge.  And I'll investigate those other comments. Thanks!

**Comment by robhudson** [comment]
Updated after feedback. I will wait for Travis then merge.

**Pull request merged**
