### PR TITLE
Make headline link to latest unfitered results

### PR DESCRIPTION
**Pull request by anaran**

### CODE REVIEW

**Comment by anaran** [comment]
Managed to cram a typo into that short commit message. Hope that is OK.

**Comment by anaran** [comment]
- Corrects commit message typo
- Addresses review feedback from sheppy in \#mdn (move a element inside h1)
- Squashes commits

**Comment by groovecoder** [comment]
Thanks @anaran. Sorry for the slow review time. Can you also specify what bug # you're working on with this?

**Comment by anaran** [comment]
Hi! This time I did not report an issue and thought to just fix it instead.
Is that OK?

**Comment by groovecoder** [comment]
We need some kind of bug # to include in the commit message, per [our CONTRIBUTING guidelines](https://github.com/mozilla/kuma/blob/master/CONTRIBUTING.md). Were you working on another bug when you saw this? Or you can file a quick bug just for this fix.

**Comment by anaran** [comment]
Have there been major changes to the repo?

For `link_latest_unfiltered` it tells me

```
This branch is 1 commit ahead, 213 commits behind mozilla:master
```

**Comment by groovecoder** [comment]
Yeah, you'll want to rebase this branch on the latest master. I don't think anyone has been in `revisions.html` so there shouldn't be any conflicts.

**Comment by anaran** [comment]
How about now, does it look right to you too?
The main delay was from me trying to get a local clone in order.

**Comment by groovecoder** [comment]
@anaran - this is looking good. I'll give it the final review and merge after a couple meetings ...

**Pull request merged**
