### PR TITLE
Bug 1503923, additional page variations for performance experiment

### PR DESCRIPTION
**Pull request by schalkneethling**
Adds additional page variations as requested in the doc:

With inlined/unused CSS and iframed interactive examples
* Without sidebar elements
* Without contributor list
* Without compat data table (and no JS/CSS loaded conditionally)

@hobinjk r?

### CODE REVIEW

**Comment by schalkneethling** [comment]
@hobinjk Do not review this yet. I misunderstood @atopal. Will update the PR with the correct variations and ping you when ready.

**Comment by schalkneethling** [comment]
@hobinjk Ok, this is ready for review. Thanks!

**Comment by schalkneethling** [comment]
Thanks @hobinjk will take a quick look.

**Comment by schalkneethling** [comment]
@hobinjk updated. Prettier was not being its usual helpful self, but instead messed up the minified code ;(

**Comment by schalkneethling** [comment]
> hopefully not js-ie-event-load-end

I do not believe so as some of these do not have an IEx at all. Thanks for the review @hobinjk

**Comment by atopal** [comment]
> > hopefully not js-ie-event-load-end
> 
> I do not believe so as some of these do not have an IEx at all. Thanks for the review @hobinjk

For those that don't have an IEx, we don't need those numbers, but we do want them for the pages that have an IEx.

**Pull request merged**
