### PR TITLE
Fix bug 1265151

### PR DESCRIPTION
**Pull request by bychek-ru**
It works fine!

### CODE REVIEW

**Comment by jwhitlock** [comment]
Please combine these commits and force-push. Let me know if you need help.

**Comment by jwhitlock** [comment]
@bychek-ru alternatively I can squash on merge

**Comment by bychek-ru** [comment]
@jwhitlock Please do if you can

**Comment by jwhitlock** [comment]
@bychek-ru ok, first time I used that. Take a look at https://help.github.com/articles/using-git-rebase/ - it's a good introduction to ``git rebase``

**Pull request merged**
