### PR TITLE
the old link <https://kuma.readthedocs.org/en/latest/installation-vagrant.html> is returned error page

### PR DESCRIPTION
**Pull request by FrankBian**

### CODE REVIEW

**Comment by groovecoder** [comment]
Thanks @FrankBian. Can you squash these into a single commit please?

**Comment by darkwing** [comment]
@FrankBian Here's a quick guide I've created to show you how to squash commits if you haven't done so before:  http://davidwalsh.name/squash-commits-git

**Comment by FrankBian** [comment]
thanks @darkwing  

I think I should get more git skills ~

**Comment by jezdez** [comment]
Thanks @FrankBian!

**Pull request merged**
