### PR TITLE
Cache fixes

### PR DESCRIPTION
**Pull request by jezdez**

### CODE REVIEW

**Comment by robhudson** [comment]
A comment and a question. Code changes look fine on the surface but I don't have enough knowledge of the code to really understand the changes.

**Comment by groovecoder** [comment]
Code changes look fine to me too. I'll spin this branch up on some local demos & docs with templates in my vm to spot-check thoroughly.

**Comment by groovecoder** [comment]
Spot check with demos & docs & templates all work well.

**Comment by groovecoder** [comment]
Just needs a rebase?

**Pull request merged**
