### PR TITLE
Bug 1116343: Remove unused dependencies.

### PR DESCRIPTION
**Pull request by ubernostrum**
:no_entry: until #2997 merges and pushes

This is a first pass, using the list @jezdez posted in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1116343).

### CODE REVIEW

**Comment by groovecoder** [comment]
Whoa, this will be great to get rid of these. Did you scan all of the `requirements` files to keep them in sync too?

And IIRC we'll need to babysit this push and manually remove the submodule directories?

**Comment by ubernostrum** [comment]
Updated with requirements files updates.

And yes, I believe we will have to babysit this.

**Comment by groovecoder** [comment]
The spot-check works great on my machine. The only extra thing I had to do was to delete the `vendor/src/*` directories that were removed.

But, I noticed [the `chief_deploy.py` script already uses `git checkout -f`](https://github.com/mozilla/kuma/blob/master/scripts/chief_deploy.py#L22) which seems to remove the directories. :clap: So, I don't expect any issues on the stage & prod deploys. I'm not sure what [the `pull` during dev deploy](https://github.com/mozilla/kuma/blob/master/scripts/update_site.py#L18) will do ...

**Comment by groovecoder** [comment]
:no_entry_sign: until https://github.com/mozilla/kuma/pull/2997 merges and pushes.

**Comment by groovecoder** [comment]
Now that #2997 has merged, this needs a rebase. :cry:

**Comment by jezdez** [comment]
Merged in d0d848dda9f4d761262c441a553ef0cdbc1e86a2

**Pull request closed without merging**
