### PR TITLE
Fixes #5860, improve Sass build tooling

### LINKED ISSUE #5860: Improve Sass build tooling
**Summary**

Local development for the new front end has improved a lot but the Sass portion has lagged behind. This can and does cause friction for both pull request review and general front-end development.

**Audience**
All developers contributing to the codebase.

**Rationale**

I, for one, regularly have to run the entire `docker-compose exec web make build-static` when making changes to the Sass files. This is slow and often leads to Docker slowing down to a crawl.

We do have a Gulp task but it has become very unreliable.

**Workaround**
As described in rationale

**Proposal**
Simplify how we build our CSS from Sass by using `node-sass-chokidar` directly instead of via yet another build tool. There are also some changes we can make to the "old" Sass source to make better use of Sass partials.

### PR DESCRIPTION
**Pull request by schalkneethling**
This allows us to do `npm start` and be off to the races for local development.

### CODE REVIEW

**Comment by tobinmori** [comment]
can i close this @schalkneethling ?

**Comment by schalkneethling** [comment]
> can i close this @schalkneethling ?

Nope :) This will be ready for review today.

**Comment by schalkneethling** [comment]
@callahad Once this PR lands we can simply run `npm start` and everything from React to Sass will be watched and built on save so, no more `docker-compose exec web make build-static` between each change to a Sass file.

In a separate commit I will remove `Grunt` and update the docs.

**Comment by callahad** [comment]
I really wish I could create a merge commit instead of squashing these and losing the separation between the sass reorg and gulp removal commits.

Any idea why we prohibit merge commits in our GitHub settings? (cc: @peterbe @escattone)

**Pull request merged**
