### PR TITLE
[Bug 1274063] Update ckeditor to 4.5.10 as well as plugins

### PR DESCRIPTION
**Pull request by safwanrahman**
#3932 Merged.
Too big changes. most of the thing is auto-generated with ``build.sh``

Just change
```
CKEDITOR_VERSION="4.5.10"

CKBUILDER_VERSION="2.3.1"
```

parameter in ``build.sh`` and run the script.

As it is frontend, @stephaniehobson r?

### CODE REVIEW

**Comment by jwhitlock** [comment]
I missed a change to ``build.sh``. The line that removes ``ckeditor/.git`` needs to be after the revision is parsed, and should look like this:

```
echo "Pulling down CKEditor from GitHub..."
rm -rf ckeditor/
git clone -b $CKEDITOR_VERSION --single-branch --depth=1 https://github.com/ckeditor/ckeditor-dev.git ckeditor


# Use the ckeditor-dev commit hash as the revision.
cd ckeditor/
rev=`git rev-parse --verify --short HEAD`
cd ..
rm -rf ckeditor/.git
```

If the ``rm -rf ckeditor/.git`` line is in the original place, then ``git rev-parse`` will pick up the *kuma* git revision, not the CKEditor git revision.

I'll need you to:

1. Fix ``build.sh`` (including fixing ``s/User/Use/`` in the comment to say ``# Use the ckeditor-dev...`` instead of ``# User the coeditor-dev...``
2. Rebuild CKEditor

You should update your current commit, with a force-push, rather than add a second commit.

When I rebuilt CKEditor, there were additional files in ``build/ckeditor/samples/old``. If you have these as well, they should be added to the commit.

Once we have a reliable CKEditor build, then we'll see if version 4.5.10 broke editing.

**Comment by safwanrahman** [comment]
@jwhitlock Updated. Can you please check?

**Comment by jwhitlock** [comment]
Rebuilt files match, except for a timestamp which the builder inserts to make me crazy. I tested editing on Safari, Firefox, and Chrome, and clicked all the buttons, appears to work.

+r from me.  Handing off to @stephaniehobson for more testing or merge.

**Comment by stephaniehobson** [comment]
Spot check looks good. Excited to see this since I have another (small) PR waiting on it.

**Pull request merged**
