### PR TITLE
Bug 1217208 - Fix completely broken email template

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by groovecoder** [comment]
I can haz tests? There's a small `tests.py` file in the app that could grow a test class like the others we have to test emails?

**Comment by robhudson** [comment]
Good idea. I plucked this out of a bigger PR. I'll add some tests that would have caught this prior to this change.

**Comment by groovecoder** [comment]
Spot-check works at least though.

r+

**Comment by robhudson** [comment]
Updated. It was actually even more broken. Now all should be good.

**Pull request merged**
