### PR TITLE
Bug 1206309: Listen for touch event on cells.

### PR DESCRIPTION
**Pull request by stephaniehobson**

### CODE REVIEW

**Comment by darkwing** [comment]
Wont this trigger two events?  What isn't `click` catching?

**Comment by stephaniehobson** [comment]
Because `<td>` isn't normally clickable and there is a hover effect on the `<td>` the first tap is being treated as a hover and the second tap is being treated as a click :/ I want the first tap to be treated as a click. 

I added the preventDefault to stop a click from being triggered as well, it works in the iOS simulator.

**Comment by darkwing** [comment]
Looking

**Comment by darkwing** [comment]
R+!

**Pull request merged**
