### PR TITLE
Bug 1490727: Cancel subscriptions when a user is deleted

### PR DESCRIPTION
**Pull request by jwhitlock**
*This is an update of PR #5139 after rebasing on current master.*

When a User is deleted all subscriptions will be canceled. This uses the utility function ``cancel_stripe_customer_subscription``, which is also used when a User cancels their subscription subscription.

I changed a few other things as well, which could be broken up into more PRs if this one is too big:

* The utility functions ``get_stripe_customer_data`` and ``cancel_stripe_customer_subscription`` took a username and email, for the sole purpose of logging them if Stripe returned an error. I've removed the error handling from these functions and moved it to the ``recurring_payment_management`` view, which is the only function that uses these utilities.
* I've adjusted the error handling as well, to gracefully handle all Stripe API errors by logging them and acting like the user has no subscription. Previously any error, including syntax errors, would be treated the same way.
* Added error-handling tests for the view, and tests for the utility functions I touched.
* Fixed Django 1.11 deprecations and Python 3 issues

### CODE REVIEW

**Comment by jwhitlock** [comment]
I have to close and open the PR because our TravisCI integration was broken when this was opened. Sorry for the noise...

**Comment by jwhitlock** [comment]
This is a payments PR, which @schalkneethling has been handling, but it is a lot of Python, so maybe @escattone is a better reviewer. There are some Python 3 changes needed to payments, so this may be a blocker for Python 3 work (or will need a rebase after).

**Comment by schalkneethling** [comment]
@jwhitlock Yup, because of all the Python I felt that I am not the best person to review this. Would be great if @escattone has time to review this. Thanks!

**Comment by jwhitlock** [comment]
OK back to you @escattone :) I still consider review and merging a low priority, since 1) user deletion is rare, and 2) we can manually cancel subscriptions if needed. @Atopal may give it a different priority.

**Comment by atopal** [comment]
+1 to what John said. Obviously useful, but not urgent.

**Pull request merged**
