### PR TITLE
Fix Bug 1156233 - zebra stripe tables

### PR DESCRIPTION
**Pull request by openjck**
Supersedes #3231 with a rebase so that we can avoid switching between Puppet and Ansible when testing this change.

This is ready for testing but needs approval from the writing team before being merged.

### CODE REVIEW

**Comment by darkwing** [comment]
Why does this need writing team approval?  They aren't creative directors.

**Comment by openjck** [comment]
From #3231:

> Needs an okay from the content team since it is indiscriminately applied to all tables.

**Comment by stephaniehobson** [comment]
Because I'm not a creative directory either?

**Comment by darkwing** [comment]
I think of you as one, but meh, OK

**Comment by openjck** [comment]
Looks great to me.

I agree that there isn't a clear decision-maker here. I would feel comfortable merging it without consulting the writers. I think we have as much of a stake as they do.

**Comment by stephaniehobson** [comment]
They are the ones who asked for it, I don't want to cause them problems or fail to fix the problem. I've already had feedback that it shouldn't be applied to singled column tables (that complicated selector is about to get more complicated!)

**Comment by openjck** [comment]
Works for me! :smile:

Everything looks good to me, so we can merge if/when we get approval from the writers.

**Comment by stephaniehobson** [comment]
Gonna adjust this and open a new one.

**Pull request closed without merging**
