### PR TITLE
bug 1194482 - Live sample don't send code to service if code comes from another page

### PR DESCRIPTION
**Pull request by JeremiePat**
The `EmbedLiveSample` allows to embed a sample that comes from a remote page. This patch make sure that in such case the proper code is retrieve from the right page before sending it.

### CODE REVIEW

**Comment by darkwing** [comment]
Can you put together a page on staging that has a variety of code sample formats so we can test this out?

**Comment by JeremiePat** [comment]
Sir, yes sir.
Here it is:
* https://developer.allizom.org/en-US/docs/User:Jeremie/Live_Sample_Tests (same page call)
* https://developer.allizom.org/en-US/docs/User:Jeremie/Live_Sample_Remote_Call (remote call)

**Comment by JeremiePat** [comment]
Arg! I screw up my branch with unwanted merge. I'll fix that tomorrow.

**Comment by darkwing** [comment]
Checking this out

**Comment by darkwing** [comment]
@JeremiePat The first test looks great but it looks the the second one got nuked from staging :(  Can you provide me the content or re-add the doc?  Sorry :(

**Comment by JeremiePat** [comment]
Done :)

**Comment by darkwing** [comment]
Works for me!  Thank you @JeremiePat !

**Pull request merged**
