### PR TITLE
Bug 842340 - Fix template parse error for some document titles

### PR DESCRIPTION
**Pull request by sanijajoy**
Fix "kuma/wiki/templates/wiki/includes/document_macros.html" via create pull request

### CODE REVIEW

**Comment by sanijajoy** [comment]
fix conflicts via commit

**Comment by sanijajoy** [comment]
request write access via commit

**Comment by jwhitlock** [comment]
Spam pull request of https://github.com/mozilla/kuma/commit/985d03713185dccd9666a6d5f0c16cad6c97e293.

**Comment by sanijajoy** [comment]
Spam pull request of 985d037. via vommut

**Comment by sanijajoy** [comment]
Spam pull request of 985d037. via comment

**Pull request closed without merging**
