### PR TITLE
Fix Bug 1186655: retina version of 10th anniversary logo

### PR DESCRIPTION
**Pull request by stephaniehobson**

### CODE REVIEW

**Comment by darkwing** [comment]
That looks miiiiiiiiiiiles better but at mobile level the entire sprite displays:

**Comment by stephaniehobson** [comment]
Good catch, thanks, updated.

**Comment by darkwing** [comment]
Now I see this one the homepage:

**Comment by stephaniehobson** [comment]
Updated.

**Comment by darkwing** [comment]
Perfect!  R+!

**Pull request merged**
