### PR TITLE
Upgrade some dependencies

### PR DESCRIPTION
**Pull request by jezdez**
Refs bug 1209185 and is supposed to simplify #3525.

### CODE REVIEW

**Comment by robhudson** [comment]
:boom: Nice. If tests pass and spot check local testing looks good, ship it!

**Comment by groovecoder** [comment]
Selenium tests passed on https://github.com/mozilla/kuma/commit/3f709333edb061deecb019c2dd8596ed3d20bc93. Are we trying to update everything in this branch before we merge? Should django 1.8 go before or after this?

**Comment by jezdez** [comment]
1.8 should come after this, I think since many of the updates fix issues with 1.8.

**Comment by jezdez** [comment]
I wasn't trying to update all deps, most of those were easy and I left the hard ones like mock outdated for now.

**Comment by groovecoder** [comment]
Tests and selenium tests still pass. I tried merging this and the django-1.8 branch, but it needs django-jinja/JINJA_CONFIG conflict resolutions that I'm not sure how to make.

@robhudson - if you're good with merging and deploying this before 1.8, I'll let you do it.

Nice work @jezdez !

**Comment by jezdez** [comment]
Ah, yeah, sorry about that, waffle started to use a Jinja2 extension instead their jingo specific helper.

**Pull request merged**
