### PR TITLE
bug 1518653: Update newrelic agents

### PR DESCRIPTION
**Pull request by limed**
Update newrelic agent for python from 3.2.1.93 -> 4.18.0.118

Update newrelic agent for nodejs from 4.13.1 -> 5.9.0

### CODE REVIEW

**Comment by peterbe** [comment]
@limed How did you execute the npm update command? The package-lock.json changed dramatically.

**Comment by limed** [comment]
> @limed How did you execute the npm update command? The package-lock.json changed dramatically.

I literally just pulled the `kuma_base` docker image and ran (on the kuma directory)

```
# docker run --rm -it -v ${PWD}:/app mdnwebdocs/kuma_base:${image hash} bash
# cd /app
# npm update newrelic
```

**Comment by escattone** [comment]
@limed you can use [bug 1518653](https://bugzilla.mozilla.org/show_bug.cgi?id=1518653), so just prefix each of your commit messages with `bug 1518653: `.

**Comment by limed** [comment]
Also resolves mdn/infra#223

**Pull request merged**
