### PR TITLE
Disable content experiment, interactive examples

### PR DESCRIPTION
**Pull request by jwhitlock**
We want to advertise the new interactive examples in the next developer newsletter, so we should deactivate the experiment so we can link to it.

### CODE REVIEW

**Comment by schalkneethling** [comment]
r+ 🦆

**Comment by atopal** [comment]
Please don't stop the A/B test. The newsletter will link to the forum post. We can remove those referrers if necessary.

**Comment by atopal** [comment]
Please don't stop the A/B test. The newsletter will link to the forum post and we can report on organic traffic only, but we could use some qualitative feedback, that we'll hopefully get in the forum thread.

**Comment by jwhitlock** [comment]
OK

**Pull request closed without merging**
