### PR TITLE
Fix Bug 1227960 - Add missing top "Previous" link to Revision History

### PR DESCRIPTION
**Pull request by anaran**
Use same proven logic as "to" radio button.

### CODE REVIEW

**Comment by anaran** [comment]
Evidently things aren't as simple as they could be:

https://travis-ci.org/mozilla/kuma/jobs/93356471#L3303

[get_previous](https://github.com/mozilla/kuma/blob/3355425fc2cfe157394e0cd9e9e266eae1eab132/kuma/wiki/views/list.py#L186) is conditional on a mysterious `pk` property.

Any advice?

**Comment by anaran** [comment]
The link into the log file does not work for me, I have to scroll or search to line 3303 manually,

**Comment by groovecoder** [comment]
Yeah, this is trickier than it should be ...

* The list view uses a custom `get_previous` transform on the QuerySet to only get approved revisions. (This is old code from SUMO where revisions have to be approved before they are published. On MDN, we auto-approve every revision and rely on post-publish editorial control to catch bad content & actors.) It also skips `current_revision.pk == previous_revision.pk` which is probably the actual cause of this bug.

* We have a [`Revision.previous`](https://github.com/mozilla/kuma/blob/8ef038905a99adfc3dd7b736a87ecb3ad3e0d1c8/kuma/wiki/models.py#L1759-L1770) property that we use, but it's expensive because it runs an additional query on the revisions table and sorts it by date to find the latest revision.

I would suggest trying to remove the `current_revision.pk == previous_revision.pk` condition from the `get_previous` queryset transform function. Do you have kuma running locally?

**Comment by anaran** [comment]
No don't have kuma running locally
I'm trying to do small contributions via github and CI.

**Comment by groovecoder** [comment]
Yeah, that won't work for this one. You'll need to verify it's all working locally too.

**Comment by groovecoder** [comment]
Closing this unless/until we can verify the `get_previous` change on a local instance.

If you'd like to try running a local instance, here are the installation docs:

https://kuma.readthedocs.org/en/latest/installation.html

**Pull request closed without merging**
