### PR TITLE
Fix bug 1215422

### PR DESCRIPTION
**Pull request by shiningfm**
added space and used class to fix width and center icon

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Looking good, nice find, thank you for the fix!

Travis-CI says the checks are failing but I don't think it's related to the work done here. I restarted the check, hopefully it will run properly this time and we can merge it in the morning.

**Comment by shiningfm** [comment]
Thank you for the feedback!
I was wondering if I did something wrong with the pull request or something... (never did that before ^^)

**Comment by stephaniehobson** [comment]
It occurs to me that we merged some pretty substantial changes into master today, maybe something there is interfering. Can you pull from master and rebase your branch? Let me know if you need instructions for how to do that. Thanks :)

**Comment by shiningfm** [comment]
I have very basic knowledge of Git and I don’t know how to do that, so yes any help would be welcome!

**Comment by stephaniehobson** [comment]
I assume you've been using git via the command line? Inside the repository directory run this command to get the new information from the server:
```
git fetch origin
```
And this to rebase with your changes:          
```
git rebase origin/master
```
These commands assume you used the default name of `origin` for the mozilla remote, if you didn't you'll have to use the name you gave it instead.

I don't see any reason why there should be any problems with the rebase, but if there is let me know. Thanks!

**Comment by shiningfm** [comment]
Yes I’ve used the command line.
Actually in my setup origin is my fork, and I have added upstream as mozilla remote. So I had to fetch upstream and merge in my local master.
Then I tried to rebase. There were problems with my branch being ahead, and I had to set the upstream branch before I could push to my github account… If I understand correctly, when I pushed the former branch was merged with the rebased one, but maybe I’m wrong, I don’t understand everything. Maybe you know some good tool to visualize commits, branches etc?

I just hope that I didn’t made a mess… I have to document myself a lot about git.
If what I did is not correct I will restart from the beginning, and do it right!

Should I fill a new pull request?

Thanks for your help!

**Comment by stephaniehobson** [comment]
Hm. Yes there is a problem with some extra files being in there. I think it would be easiest to create a clean branch and copy your changes over to it. Sorry for the trouble :(

**Comment by shiningfm** [comment]
I'm sorry myself for taking so much of your time...
I created a new branch, and sent a new pull request. Travis passed, so I hope it is alright!

**Pull request closed without merging**
