### PR TITLE
bug 1151523 - Disallow IFRAMEs from CKEditor

### PR DESCRIPTION
**Pull request by darkwing**
The first step in preventing IFRAMEs in CKEditor per the bug in the title.

Relevant:  http://docs.ckeditor.com/#!/guide/dev_disallowed_content

### CODE REVIEW

**Comment by darkwing** [comment]
Writers will want to ensure all of the tags they claim to need are supported, so they may want to test this on staging.

**Comment by darkwing** [comment]
I need to compare this "allowedContent" object with our bleach list.  I may need to add element.

**Comment by darkwing** [comment]
OK, looks good.

**Comment by darkwing** [comment]
NM, I need to add the MathML tags to the allowed elements list :/  Working on that now

**Comment by darkwing** [comment]
w00t!  Updated CKE's `allowedContent` to use our bleach list.  w00t!

**Comment by hoosteeno** [comment]
The cleanup is not quite done yet. This thread has more info:
https://groups.google.com/d/msg/mozilla.dev.mdc/gOpa3FcEj1E/LKLAjpDqtPQJ

This link has the status of cleanup:
https://developer.mozilla.org/en-US/docs/MDN/Plans/Remove_in-content_iframes

**Comment by hoosteeno** [comment]
Iframe cleanup is complete: https://groups.google.com/d/msg/mozilla.dev.mdc/gOpa3FcEj1E/icX_UOx5gh0J

We can merge this.

**Comment by darkwing** [comment]
@groovecoder  or @openjck  Ready to test this?

**Comment by groovecoder** [comment]
Code looks good, spot-check works.

**Pull request merged**
