### PR TITLE
Bug 1260487: Remove obsolete items from nav & homepage.

### PR DESCRIPTION
**Pull request by stephaniehobson**
- Web Platform -> Web Technologies
- Move WebExtentions under Web Technologies
- Remove Mozilla Docs and Contact from homepage
- Add Learning Area to homepage
- Remove HTML5 and CSS3 from homepage
- Add styles to vertically center single line headings in supporting browsers

### CODE REVIEW

**Comment by stephaniehobson** [comment]
@chrisdavidmills can you review the Learning Area links please?

**Comment by chrisdavidmills** [comment]
For the Learning Area links, I think it would be better if we linked the subitems to the main HTML, CSS, and JavaScript pages, e.g.

Learn/HTML
Learn/CSS
Learn/JavaScript

Could we make the link text as follows:

"Learn HTML"
"Learn CSS"
"Learn JavaScript"

**Comment by chrisdavidmills** [comment]
Also, the level 3 heading is "Learning Area" - can we change this to "Learning the Web"?

**Comment by jwhitlock** [comment]
Reassign me for review when you've decided on @chrisdavidmills's feedback

**Comment by stephaniehobson** [comment]
Updated with Chris' feedback:
- Links changed to recommended articles and links
- Found "Learn the web" article had been re-named to "Learning web development" in production so changed link to match
- Changed list title to "Learning" since "area" doesn't appear anywhere else on the site and Chris' didn't like it. Did not append "the web" since that doesn't appear anywhere else on the site anymore either and I don't like it :P

**Comment by chrisdavidmills** [comment]
Looks good to me. Thanks!

**Pull request merged**
