### PR TITLE
Bug 1157937 - Track TOC clicks

### PR DESCRIPTION
**Pull request by stephaniehobson**

### CODE REVIEW

**Comment by darkwing** [comment]
How about this instead?

```
/*
    Track Clicks on TOC links
*/
$('#toc').on('click', 'a', function() {
    var $thisLink = $(this);

    mdn.analytics.trackEvent( {
        category: 'TOC Links',
        action: $thisLink.text(),
        label: $thisLink.attr('href')
    });
});
```

**Comment by darkwing** [comment]
Kicked the Travis job, looks like a transient error.

**Comment by groovecoder** [comment]
:+1: for the `$('#toc').on('click', 'a')` event binding.

**Comment by stephaniehobson** [comment]
I'm not arguing, I just wanting to understand but I don't know how to ask this question without sounding petulant so, sorry: Could someone please explain to my why this is better?

**Comment by groovecoder** [comment]
I like it because it's less nested code and easier for me to read.

**Comment by darkwing** [comment]
I prefer my method because:

-  I'm using event delegation on the TOC, assigning one event handler on the parent instead of assigning an event to every link within it.

-  You don't need to check for `.length` for methods directly on the jQuery return object -- nothing will happen if the selector matches nothing.

-  You don't need an `each` for jQuery object methods -- it's an implied loop for all matches.

**Comment by groovecoder** [comment]
This is assigned back to me ... want me to pick it up?

**Comment by stephaniehobson** [comment]
Updated, leaving it to @groovecoder to review.

Sorry for the slow update, I've had other things on my mind. And thinks for the explanations :)

**Pull request merged**
