### PR TITLE
fix bug 1126382 - Upgrade CKEditor to 4.4.7

### PR DESCRIPTION
**Pull request by darkwing**
As discussed via email.

### CODE REVIEW

**Comment by darkwing** [comment]
Ping!  Anyone want this?  @groovecoder ?

**Comment by openjck** [comment]
I've been busy with Gulp, but can look at this today.

**Comment by openjck** [comment]
This changes more than I thought. When we updated CKEditor last month, did we come up with a standardized way of testing updates? Would you recommend having the writers test this out on staging for a while?

**Comment by darkwing** [comment]
This has been pushed to mozilla repo

**Comment by openjck** [comment]
https://github.com/mozilla/kuma/tree/1126382-ckeditor-upgrade

**Comment by groovecoder** [comment]
@openjck @darkwing - can one of you coordinate a staging push of the branch for content team to test?

**Comment by openjck** [comment]
I'll coordinate today.

**Comment by openjck** [comment]
Are we ready to push? I remember someone saying in the meeting that something else needed to be pushed first.

**Comment by groovecoder** [comment]
No bugs filed in 24 hours of stage testing. One more rebase and :shipit:

**Comment by openjck** [comment]
Rebased with #3053.

**Pull request closed without merging**
