### PR TITLE
bug 1177264 - waffle cleanups

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by darkwing** [comment]
What do we plan on doing when fellowship opens back up?  Keep swapping messages with PRs?

**Comment by groovecoder** [comment]
When we do the next fellowship program, there are sure to be updates to the program and to this page for it. So, I anticipate we'll have a future PR that could also restore a waffle flag for the time-sensitive messaging. Does that work?

**Comment by groovecoder** [comment]
@darkwing - can you also check me on my removals of the js/client waffle flag code?

**Comment by darkwing** [comment]
Looking

**Comment by darkwing** [comment]
R+ :+1:

**Pull request merged**
