### PR TITLE
bug 1136741 - Clean out waffle flags

### PR DESCRIPTION
**Pull request by groovecoder**
Makes a number of waffled features permanent:
* GitHub login
* Firefox 10th anniversary demo style
* Derby closed
* GA outbound link tracking
* Web font loader

### CODE REVIEW

**Comment by darkwing** [comment]
Looking

**Comment by darkwing** [comment]
All spot-checks work, just waiting on Travis...

**Comment by groovecoder** [comment]
Docs build on Travis failed trying to download dependencies. :cry: Kicked it ...

**Comment by groovecoder** [comment]
Travis fixed.

**Comment by darkwing** [comment]
Tests pass, everything spot-checked.  R+

**Pull request merged**
