### PR TITLE
fix bug 1114649 - added draft saving feature while creating new document

### PR DESCRIPTION
**Pull request by kvsingh**

### CODE REVIEW

**Comment by openjck** [comment]
Hi Karanveer. Thanks so much for submitting this contribution.

The feature request appears to be about automatically saving drafts on the *New* page as content is being written, just like most email programs automatically save drafts as content is written. These changes don't add that feature.

I'm glad you're excited to make this change. Take a look at the links in the [first bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1114649#c0). They should provide some direction.

**Comment by groovecoder** [comment]
Thanks for the updates @kvsingh - is this ready for review again? Can you clean up the branch so it only includes the `new_document.html` changes from https://github.com/kvsingh/kuma/commit/ba94fbb64947278575d8f3d4e113381a74286d8a?

**Comment by kvsingh** [comment]
Yes, I will clean up my branch and make it ready for review as soon as possible.

**Comment by kvsingh** [comment]
I have made the changes and now this is ready for review.

**Comment by groovecoder** [comment]
Nice work! Spot-check looks good and the code is minimal.

**Pull request merged**
