### PR TITLE
chore(editorconfig): Fix `.jsx` indentation configuration

### PR DESCRIPTION
**Pull request by ExE-Boss**
**Q:** Should I set `indent_style` and `indent_size` for all files? And if so, what should I set it to?

### CODE REVIEW

**Comment by peterbe** [comment]
> **Q:** Should I set `indent_style` and `indent_size` for all files? And if so, what should I set it to?

Is it not already so?

Because I don't think I understand the question, I'll hold off on merging this.

**Comment by ExE-Boss** [comment]
@peterbe
> > **Q:** Should I set `indent_style` and `indent_size` for all files? And if so, what should I set it to?
>
> Is it not already so?

No, it’s not:
https://github.com/mdn/kuma/blob/ca5062683e96f0782c5e7b3feaf7708a98574f87/.editorconfig#L4-L9

That just sets line ending behaviour.

**Comment by schalkneethling** [comment]
@ExE-Boss @peterbe Do we even need this now that we have standardized on Prettier for this project?

**Comment by ExE-Boss** [comment]
Yes, as Prettier (and **VS Code**) uses `.editorconfig` for indentation information.

**Comment by peterbe** [comment]
> Yes, as **Prettier** (and **VS Code**) uses `.editorconfig` for indentation information.

It *can*. 

The two are somewhat different in that `.editorconfig` helps the *editor* how it should do stuff. But `prettier` in the final authority.

**Pull request merged**
