### PR TITLE
Use isort for improved import order consistency

### PR DESCRIPTION
**Pull request by jezdez**
https://bugzilla.mozilla.org/show_bug.cgi?id=1218957

### CODE REVIEW

**Comment by robhudson** [comment]
In general I :heart: this. I've used isort while editing individual files for awhile and am in agreement with this.

The errors appear to be missed application of isort. Perhaps something with isort running from a virtualenv? The suggested changes from the output look correct and are what I see locally as well.

Once those changes are applied, r+.

Personally I'm going to add the git hook after this lands to catch errors before waiting on Travis to find them.

**Comment by jezdez** [comment]
Hmm, not sure what's wrong.

**Comment by jezdez** [comment]
Can someone else try fixing this, I've been stabbing at this for too long

**Comment by robhudson** [comment]
@jezdez I got the isort fixed by manually fixing the few files that were missed by running `isort --apply`, but no idea what's up with the tests.

**Comment by jezdez** [comment]
@robhudson Yeah, I don't know man. I can try to pick it up again

**Comment by robhudson** [comment]
I tried and failed also. I think we should just close it and perhaps work towards this as we make edits over time. Whatever is causing this problem will likely rear its head somewhere along the way and be easier to find.

**Pull request closed without merging**
