### PR TITLE
Fix bug 1078186: Redirect static canvas examples to wiki pages

### PR DESCRIPTION
**Pull request by Elchi3**
This looks ugly, but having these old static pages as top results in Google is ugly, too. Especially now that we have better docs in the wiki :) See https://bugzilla.mozilla.org/show_bug.cgi?id=1078186

I am wondering if this will actually work, given there is also this in line 12:
`RewriteRule ^samples(.*) data/www/samples$1 [L]`

### CODE REVIEW

**Comment by groovecoder** [comment]
Yes - mod_rewrite will process them top-to-bottom, so you'll have to put the more specific rewrite regex's above the more generic one.

**Comment by groovecoder** [comment]
ping @Elchi3 - are you able to move the rewrites up above the generic `^samples(.*)` one?

**Comment by Elchi3** [comment]
Sorry for the delay, was attending a conference :) I moved the rules up above the generic rules and I tested some of the URLs using this tool: http://htaccess.madewithlove.be/.

**Comment by groovecoder** [comment]
Looking good. Need to add [the `NE` flag](http://httpd.apache.org/docs/trunk/rewrite/flags.html#flag_ne) to all the `RewriteRule`s so the `#` characters aren't escaped away.

**Comment by groovecoder** [comment]
E.g.,
```
RewriteRule ^samples/canvas-tutorial/2_1_canvas_rect.html$ docs/Web/API/Canvas_API/Tutorial/Drawing_shapes#Rectangular_shape_example [NE,R=301,L,NC]
```

**Comment by Elchi3** [comment]
Updated.

**Comment by groovecoder** [comment]
Looks good, thanks!

**Pull request merged**
