### PR TITLE
fix bug 1149282 - Ensure proper paren placement in locales list

### PR DESCRIPTION
**Pull request by darkwing**
The parens look wonky in RTL in this list.  Fixing it.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Apparently this is quite complicated to fix... I'm going to email someone on the l10n team and ask for advice.

**Comment by stephaniehobson** [comment]
Talked to Pascel on the #l10n team and he suggests the bidi tag go around the locale as well as the abbreviation. I like how this makes the RTL languages easier to spot in the list.

```
<bdi>{{ locale[1] }}  ({{ locale[0] }})</bdi>
```

**Comment by darkwing** [comment]
Updated @stephaniehobson

**Comment by darkwing** [comment]
Just kicked Travis

**Comment by stephaniehobson** [comment]
:+1:

**Comment by stephaniehobson** [comment]
Wrong button >_<

**Pull request merged**
