### PR TITLE
Bug 1218466: Queue errors before GA loads.

### PR DESCRIPTION
**Pull request by stephaniehobson**
Try to avoid missing anything that happens before GA initializes.

### CODE REVIEW

**Comment by groovecoder** [comment]
A 9-line variation for the same 22 lines of logic?
```
            if (ga) {
                // GA blocked or not yet initialized - strip callback from data
                data.hitCallback = !ga.create ? null : data.hitCallback;
                ga('send', data);
            }
            // Always execute the callback
            if (callback) {
                callback();
            }
```
Eliminates the dupe code calls for `ga('send', data)` and `callback()`.

**Comment by stephaniehobson** [comment]
The ga send function will log and execute the callback if we leave it in the data.

**Comment by darkwing** [comment]
```
data.hitCallback = (ga.create ? data.hitCallback: null);
```

I'd roll with positive first.

**Comment by groovecoder** [comment]
@stephaniehobson I think my ternary logic there (or @darkwing's positive logic) should remove `hitCallback` from `data` the same as the existing logic.

**Comment by stephaniehobson** [comment]
But we're always executing the fallback in your proposal, correct? In cases where we pass the callback to ga sucessfully the callback will be executed twice.

**Comment by groovecoder** [comment]
Aha, yeah I overlooked that.

r+ :smile:

**Pull request merged**
