### PR TITLE
bug 1139490 - remove GitPython

### PR DESCRIPTION
**Pull request by groovecoder**
Now that we use django-pipeline instead of jingo-minify.

This ┬──┬﻿ ¯\_(ツ) @jezdez [5-month-ago (╯°□°）╯︵ ┻━┻)](https://github.com/mozilla/kuma/pull/3073#commitcomment-11515254)

### CODE REVIEW

**Comment by jezdez** [comment]
giphy

**Comment by jezdez** [comment]
r+

**Comment by openjck** [comment]
No errors to report from the front-end. r+ from me too.

**Comment by openjck** [comment]
anigif_enhanced-buzz-29357-1386297905-2

**Pull request merged**
