### PR TITLE
npm audit fix upgrades

### PR DESCRIPTION
**Pull request by peterbe**
This is the outcome of running `npm audit fix`. 

It's practically impossible to code-review review this but the ultimate test is if the site is working. Also, I don't think we should land this till we have a working TravisCI.

### CODE REVIEW

**Comment by peterbe** [comment]
Upgrading react-svg-loader took a good chunk of the warnings away. 

Mind you, for version 3.0.0, this issue: https://github.com/boopathi/react-svg-loader/issues/257

**Comment by davidflanagan** [comment]
This PR doesn't include the react-svg-loader update. That should be safe to do ASAP because it only affects the React code that is not exposed to users yet.

The others seem likely to just work fine, and I'd expect that any issues would be discovered in dev or staging, so I agree that we should just do this once the Travis fixes are up.

**Comment by peterbe** [comment]
Turns out, I had forgotten to git push my change to version of react-svg-loader. 
Also, for the packages I touched, I updated the version pins to be exact. Wasn't sure how to do that with the npm cli so I just edited package.json and removed the little `^` prefix.

**Comment by ExE-Boss** [comment]
See also https://github.com/mdn/kumascript/pull/1127, which does the same thing, but for **KumaScript**.

**Comment by peterbe** [comment]
@davidflanagan Now will 101% CI passing

**Comment by peterbe** [comment]
@davidflanagan So can I merge it now?

**Comment by davidflanagan** [comment]
@peterbe: I'm assuming that you've tried running locally and things still seem to be working, and that you've checked release notes for the upgraded packages to verify that there aren't any big breaking changes, so yes, please go ahead.

I tend to just stick to r+ and leave the merging to the author, though I'm a little unclear on what the right protocol around that is

**Comment by peterbe** [comment]
>  running locally and things still seem to be working, and that you've checked release notes

No. The only thing I did was start it up and visit `http://mdn.localhost:8000` And/or the beta site. Can't remember.

Turns out I failed to mention it and got caught up in git/travis chores. What I *wanted* to mention was "I need your help checking that this didn't break anything". 

I'll try to make an effort tomorrow testing this a bit more in detail.

**Comment by peterbe** [comment]
Now I remember why I failed to mention the need for help! When preparing this patch I noticed that react-svg-loader [didn't have a CHANGELOG](https://github.com/boopathi/react-svg-loader/issues/257) and that I was going to come back to here once that got figured out. Ugh!

**Comment by peterbe** [comment]
This was a little tricker than I thought it would be. I'm going to attempt with [this PR](https://github.com/mozilla/kuma/pull/5405). Renovate's config is powerful but at the cost that it's a lot to learn.

**Pull request merged**
