### PR TITLE
Fixes bug 632204 - Remove reCAPTCHA

### PR DESCRIPTION
**Pull request by utkbansal**
* removes the captcha form field from forms and template
* removes django-recaptcha submodule
* remove the recaptcha settings from settings.py

### CODE REVIEW

**Comment by utkbansal** [comment]
@openjck Why did it fail?

**Comment by groovecoder** [comment]
@utkbansal - the "Details" link to the failed Travis job shows the test failure output. You should run the tests locally to see if you can reproduce the test failure.

**Comment by openjck** [comment]
The message of the day in Vagrant provides instructions for running tests. You can also run `cat /etc/motd` to see the message.

**Comment by utkbansal** [comment]
The build failed because 'ImportError: No module named captcha'. I have removed captcha as it is no longer required. Please help me fix this, I have no idea what to do.

**Comment by groovecoder** [comment]
You forgot to remove the `captcha` app from `INSTALLED_APPS` in `settings.py`. So `jingo`/jinja is still trying to load it.

**Comment by openjck** [comment]
We can also remove RECAPTCHA settings from settings_local.py:

https://github.com/mozilla/kuma/blob/master/puppet/files/vagrant/settings_local.py#L21-23

**Comment by groovecoder** [comment]
@utkbansal - do you have time to finish this up? (You'll also need to re-word the commits to include "bug 632204" at the beginning of each commit message.

**Comment by utkbansal** [comment]
Sorry for the delay. I'll give it one more try.

**Comment by groovecoder** [comment]
Thanks for the contribution @utkbansal. I added another commit and sent https://github.com/mozilla/kuma/pull/3165 to supersede this pull request.

**Pull request closed without merging**
