### PR TITLE
fix bug 1145580

### PR DESCRIPTION
**Pull request by a2sheppy**
Added check for trailing slash and a test for this fix.

### CODE REVIEW

**Comment by a2sheppy** [comment]
Tried to be sure I had the latest code before working on this but must have missed something. Not sure how to proceed.

**Comment by openjck** [comment]
Awesome! Thanks Sheppy. You'll need to do a rebase:

1. `git remote add mozilla https://github.com/mozilla/kuma.git`
2. `git fetch mozilla/master`
3. `git rebase mozilla/master`
4. `git push -fu origin move-slug-trailing-slash-1145580`

**Comment by groovecoder** [comment]
Ah, the rebase. Basic Kuma-Fu training.
kuma-fu

**Comment by openjck** [comment]
Ha! Love it.

**Comment by darkwing** [comment]
Wow @a2sheppy, great work!

**Comment by groovecoder** [comment]
Works well. Should we also update the move page to describe the slug rules we're enforcing?

**Comment by a2sheppy** [comment]
That's a good idea. I will add that to this PR and push it again in, once my chain of meetings today is over.

**Comment by groovecoder** [comment]
Thanks @a2sheppy. @darkwing, @openjck, or @stephaniehobson want to review the style/display changes?

**Comment by groovecoder** [comment]
Assigning to @darkwing - he had the fewest other PRs assigned to him already. :wink:

**Comment by darkwing** [comment]
Superceded by:  https://github.com/mozilla/kuma/pull/3183

**Pull request closed without merging**
