### PR TITLE
Fix bug 859398: Sort tag list alphabetically

### PR DESCRIPTION
**Pull request by Elchi3**
https://bugzilla.mozilla.org/show_bug.cgi?id=859398

### CODE REVIEW

**Comment by groovecoder** [comment]
Travis error is a transient demo studio file I/O error. But I can't see how to re-run this with Travis UI anymore. :question:

**Comment by Elchi3** [comment]
I repushed, then I rebased and repushed. No new travis run is kicked off either way :-(

**Comment by groovecoder** [comment]
No worries. I'll spot-check it.

**Comment by groovecoder** [comment]
Trying to check this to see if it's using an indexed field for the `order_by` ...

**Comment by groovecoder** [comment]
```
mysql> explain  SELECT `wiki_documenttag`.`id`, `wiki_documenttag`.`name`, `wiki_documenttag`.`slug` FROM `wiki_documenttag` INNER JOIN `wiki_taggeddocument` ON (`wiki_documenttag`.`id` = `wiki_taggeddocument`.`tag_id`) WHERE `wiki_taggeddocument`.`content_object_id` = 3611 ORDER BY `wiki_documenttag`.`name` ASC;
+----+-------------+---------------------+--------+-----------------------------------------------------------+------------------------------+---------+--------------------------------------------------+------+---------------------------------+
| id | select_type | table               | type   | possible_keys                                             | key                          | key_len | ref                                              | rows | Extra                           |
+----+-------------+---------------------+--------+-----------------------------------------------------------+------------------------------+---------+--------------------------------------------------+------+---------------------------------+
|  1 | SIMPLE      | wiki_taggeddocument | ref    | wiki_taggeddocument_92733365,wiki_taggeddocument_3747b463 | wiki_taggeddocument_92733365 | 4       | const                                            |    5 | Using temporary; Using filesort |
|  1 | SIMPLE      | wiki_documenttag    | eq_ref | PRIMARY                                                   | PRIMARY                      | 4       | developer_mozilla_org.wiki_taggeddocument.tag_id |    1 | NULL                            |
+----+-------------+---------------------+--------+-----------------------------------------------------------+------------------------------+---------+--------------------------------------------------+------+---------------------------------+
2 rows in set (0.00 sec)
```
Still using a couple good indices here, so this is good to merge for me.

**Pull request merged**
