### PR TITLE
Bug 1197452: Remove unused badges stylesheet

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

**Comment by darkwing** [comment]
Should the team have a discussion, make a decision about removing all badge stuff from MDN?

**Comment by openjck** [comment]
We could. The stylesheet isn't used anywhere on the site, and we always have the option of getting it back with Git history. Luke also gave a go-ahead for removing it.

**Comment by darkwing** [comment]
R+

**Comment by groovecoder** [comment]
FWIW, we've already removed `django-badger` and its usage from the back-end and template code:

https://github.com/mozilla/kuma/commit/699a8fd33eb0e1f37a8f1c8c47780f3565fcd3c4
https://github.com/mozilla/kuma/commit/b8cff3ac71b0d43b2ecfa49b66a67a6abf0eecfe
https://github.com/mozilla/kuma/commit/8068ff61f1698383dd8adf36b1d99cf03918dbbd

**Pull request merged**
