### PR TITLE
bug 1209185 - django 1.8: authkeys migrations; reset wiki migrations; update django-constance

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
Note: these are the changes I had to make in order to make the test suite even run.

**Comment by robhudson** [comment]
Yeah, getting the test suite to run should be the first priority to help us find the next priorities. Thanks.

**Comment by groovecoder** [comment]
I created migrations for the `authkeys` app - it didn't have any before.

I tried to `squashmigrations` of the `wiki` app, but the `move_to_user` function is incompatible with the current table layout. (Kept getting errors that `userprofile` did not exist when it tried to run.) So, I just deleted the existing migrations and did a new `makemigrations` to make a new initial wiki migration. It means vms will need to be re-built, and we will need to reset the migration history on stage & prod during deploy.

**Comment by jezdez** [comment]
Yeah, squashing those migrations is a great move +1

**Comment by robhudson** [comment]
Should we do this on all apps to make it easy to update the migration meta tables (and also reset the migrations)?

**Comment by jezdez** [comment]
@robhudson good question, I think the wiki app may be a good candidate as well. Not sure about the others

**Pull request merged**
