### PR TITLE
Fix Bug 1238616: Update to jQuery 2.2

### PR DESCRIPTION
**Pull request by stephaniehobson**
Updated version of jQuery. Re-ordered the users.js package to fix an error I was seeing on the user profile edit page.

I'm having trouble running the intern tests locally, the update to FireFox 44 seems to be confounding them. I've spent the morning trying to fix the problem and need a break. I'd appreciate if the reviewer could run the tests.

### CODE REVIEW

**Comment by willkg** [comment]
I'll look at this. I need to get intern working first.

**Comment by willkg** [comment]
@robhudson Can you look at this? It needs to get run through intern and I don't have that working, yet.

**Comment by willkg** [comment]
I talked to @robhudson on IRC and he said we should push this to -stage and test it with intern there. I think we can do that tomorrow (Tuesday, January 26th).

I want to push @jezdez's stuff first, but then I can coordinate this.

**Comment by stephaniehobson** [comment]
Closed in favour of #3766.

**Pull request closed without merging**
