### PR TITLE
Bug 1370594: Outline sample code

### PR DESCRIPTION
**Pull request by stephaniehobson**
Add a border around live sample code.

- This content looks different from other page content because it is in an iframe, there should be signal  for that
- Borrowed the border colour from the interative-examples
- Renamed .scss file to better indicate what it pertains to

### CODE REVIEW

**Comment by schalkneethling** [comment]
@stephaniehobson Which page can I use to test this? There probably isn't a page available by default in the sample DB but, I can create it locally. Thanks.

**Comment by stephaniehobson** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#Examples

**Comment by stephaniehobson** [comment]
(it appears on the page just above the "open in CodePen" button.

**Comment by schalkneethling** [comment]
I have a slight concern that the contrast of the border on the white background is very low. So much so, that it is almost not visible. I wonder if it would be worth to darken it a bit? @stephaniehobson 

Other than that r+

**Comment by stephaniehobson** [comment]
Made the outline a darker grey.

**Pull request merged**
