### PR TITLE
Add Fedora/RPM instruction for Ansible

### PR DESCRIPTION
**Pull request by SphinxKnight**
Added dnf / yum installation step for Ansible for Fedora/RPM based distro

### CODE REVIEW

**Comment by groovecoder** [comment]
D'oh, this commit didn't reference the bug # ...?

**Comment by jezdez** [comment]
@groovecoder The merge commit did and registered it in the ticket.

**Comment by groovecoder** [comment]
Ah, okay. /me looks for a way to expand merge commit messages in PRs

**Comment by jezdez** [comment]
@groovecoder Sorry, I thought that it would show up here as well :-/

**Pull request merged**
