### PR TITLE
Bug 1180970 - Fixed load_documents URL pattern to refer to view callable and not view name.

### PR DESCRIPTION
**Pull request by jezdez**

### CODE REVIEW

**Comment by jwhitlock** [comment]
I need to reinstall kuma, vagrant, etc, and it will probably be a few days until I can check this.  Reassigning to @groovecoder

**Comment by groovecoder** [comment]
@jwhitlock - no prob. Why did you have to reinstall? :cry:

**Comment by groovecoder** [comment]
This fixes the first error listed in the bug, but there's another one behind it ...

To spot-check the full feature, I tried loading an export of documents - e.g., [the KumaScript autoload templates](http://kuma.readthedocs.org/en/latest/installation.html#kumascript):

1. Download [the `kumascript-autoload-modules.json` file attached to bug 1044093](https://bugzilla.mozilla.org/attachment.cgi?id=8471600&action=edit).
2. Change the "creator" values to your local username
3. Go to [the `docs/load` page](https://developer-local.allizom.org/en-US/docs/load/)
4. Try to load the `.json` file

```
  File "/home/vagrant/src/kuma/wiki/views.py", line 2326, in load_documents
    uploaded_file = request.FILES['file']
  File "/home/vagrant/src/vendor/src/django/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'file'"
[09/Jul/2015 07:43:46] "POST /en-US/docs/load/ HTTP/1.1" 500 59
```

**Comment by jwhitlock** [comment]
I was unhappy with the username chosen for me on my new laptop, and it gets baked into many, many config files.  Easiest solution appears to be to create a new user, re-init everything.

**Comment by jezdez** [comment]
@groovecoder Hm, this seems like a different bug, could we merge this and open a new ticket?

**Comment by groovecoder** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1182242.

**Pull request merged**
