### PR TITLE
Fix bug 1139670: Remove the maintenance page

### PR DESCRIPTION
**Pull request by openjck**
This is nice to have, and I honestly wish we used it more than we do.
It's much nicer than the standard black and white error message we
usually serve up when the site is down. It worked well, too, even though
IT had an unrelated hosting issue the last time they used it.

That said, we haven't been maintaining it (no pun intended) and we don't
have any maintenance planned. We can always use this code as inspiration
for future maintenance pages, but there's no good reason to let it
bitrot in the repository in the meantime.

### CODE REVIEW

**Comment by groovecoder** [comment]
Can I call **DNM** on this until we figure out if there will be site downtime during the RabbitMQ physical-to-virtual process?

**Comment by openjck** [comment]
Works for me. Happy to have a use for it. :smile:

**Comment by groovecoder** [comment]
It looks like we **will** use this sometime soon. Should we close this PR? Or maybe change it to update the maintenance page?

**Comment by openjck** [comment]
I'll make this a big rock for the week. When do we need the page to be ready?

**Comment by groovecoder** [comment]
May have some down-time on Saturday. :frowning:

**Comment by openjck** [comment]
Sounds good to me. That's plenty of time.

**Pull request closed without merging**
