### PR TITLE
Fix Bug 1238616: Update to jQuery 2.2

### PR DESCRIPTION
**Pull request by stephaniehobson**
Updated version of jQuery. Re-ordered the users.js package to fix an error I was seeing on the user profile edit page.

### CODE REVIEW

**Comment by willkg** [comment]
If it's easier, there's a bunch of git shenanigans you can do that'll update the PR with the new changes rather than open up a brand new PR.

The code changes look fine to me, but I haven't been able to get intern to run. @robhudson can run them, though so I think we should assign this to him to test out.

@robhudson Is that ok with you? Can you run intern locally or do you have to run it against -stage?

**Comment by robhudson** [comment]
I tried running them locally but didn't have much success. It'll be best to run against stage if we can do a branch push.

**Comment by stephaniehobson** [comment]
@willkg I didn't make any changes ;) I just switched the PR from a branch on my fork to a branch on this repo. Are there shenanigans for that?

**Comment by willkg** [comment]
@stephaniehobson Ohhh... I didn't understand. I thought you were tweaking the changes. I should have looked more closely.

**Comment by willkg** [comment]
^^^ I rebased the changes against the current master which has pip8/virtualenv/deploy changes. Otherwise we're undeploying @jezdez's changes and then that was getting messy on -stage.

**Comment by willkg** [comment]
I pushed the code to -stage, verified that it had jquery 2.2 (ran `$.fn.jquery` in the console) and @robhudson kindly ran the intern tests. It looks good as far as I can tell.

Given that, r+!

**Pull request merged**
