### PR TITLE
Big 1206309 - Fix cell opening.

### PR DESCRIPTION
**Pull request by stephaniehobson**
Border-bottom should be added to appropriate cells at appropriate times again.

### CODE REVIEW

**Comment by groovecoder** [comment]
@stephaniehobson - who should take this? simple enough for a dumb-dumb like me? Or does it need @darkwing or @openjck ?

**Comment by darkwing** [comment]
R+, works for me, though I am seeing a real merge coflict

**Comment by stephaniehobson** [comment]
Merge conflict should be resolved. This needs a good review again to make sure I didn't mess it up. 

I'm also seeing a the error `ReferenceError: Prism is not defined` in the console. I don't *think* it's related to anything I did?

**Comment by darkwing** [comment]
R+

**Pull request merged**
