### PR TITLE
Bug 1308322: Upgrade to selenium 3.x

### PR DESCRIPTION
**Pull request by jwhitlock**
Builds on py.test updates in #4210 with Selenium updates:

* selenium 2.53.6 -> 3.4.1: Support for GeckoDriver 0.15.0+, Firefox 52+. Many fixes
* pytest-base-url 1.1.0 -> 1.3.0: specify by env, add to metadata
* pytest-html 1.10.1 -> 1.16.0: add metadata to report
* pytest-selenium 1.4.0 -> 1.9.1: Move cloud testing credentials from default config files to new files or environment. Re-write Firefox options method. Work with metadata.
* pytest-metadata==1.3.0: New dependency of pytest-selenium

Django tests and coverage worked for me.  I was able to run the functional tests locally with Chrome and Firefox.  I tried running the Selenium hub and remote locally, but wasn't able to get it working (``KeyError: 'moz:firefoxOptions'`` issue), and Jenkins has the same issue.

**Update Sep 19, 2017**: The tests now run, and pass in Chrome, but they fail when run with ``node-firefox`` (timeouts) and when run locally (2 tests that open new URLS, maybe in a tab)

**Update Oct 6, 2017**: Selenium 3.6.0. The tests pass locally in Chrome and Firefox. They pass with ``node-chrome``, but now do not run with ``node-firefox``.

**Update Nov 7, 2017**: Selenium 3.7.1. The tests pass in Chrome (with one flaky test for a recently changed feature), and 5 test failures in Firefox.

**Update Dec 6, 2017**: Selenium 3.8.1. The tests pass in Chrome and local Firefox. I've found a way to make hover tests pass in Remote, and might be able to fix the failures.

**Update Jan 16, 2017**: Selenium 3.8.1-erbium. After breaking up ``test-dashboard``, tests pass in Chrome and Firefox. There are selective ``xfails`` for Firefox breakage around hover tests. The base functionality has been merged in other PRs, now we're down to just the Selenium 3.x update.

### CODE REVIEW

**Comment by jwhitlock** [comment]
I got the [same results in Jenkins](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/stage-integration-tests/41/console) that I did locally: 

```
        if browser_profile:
>           capabilities["moz:firefoxOptions"]["profile"] = browser_profile.encoded
E           KeyError: 'moz:firefoxOptions'
```

Bedrock appears to be using Selenium 3 - I'll see if there are configuration changes needed for our environment.

**Comment by jwhitlock** [comment]
I am wrong. There is an PR for updating to Selenium 3 (https://github.com/mozilla/bedrock/pull/4472) but it isn't merged, and appears stale.  I'll try to get this to a test case for an upstream issue.

**Comment by davehunt** [comment]
@jwhitlock Selenium Python client 3.4.1 was released today, which should solve your issue. https://pypi.python.org/pypi/selenium/3.4.1

**Comment by jwhitlock** [comment]
[Still fails](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/4/console) with selenium 3.4.1.

**Comment by jwhitlock** [comment]
Opened https://github.com/SeleniumHQ/selenium/issues/3927

**Comment by jwhitlock** [comment]
The upstream bug is marked as fixed, but is not integrated in a new release, so we're still blocked.  I'm watching the [hub](https://hub.docker.com/r/selenium/hub/) and [node-firefox](https://hub.docker.com/r/selenium/node-firefox/tags/) Docker images, and will test with the next release.

**Comment by jwhitlock** [comment]
There's a new release, and I've upgraded the packages and docker images. However, it is still not working. It appears there is a problem with settings ``w3c_capabilities``, tracked in https://github.com/SeleniumHQ/selenium/issues/3808.

**Comment by jwhitlock** [comment]
Selenium team believes the issue is fixed in master, waiting for Selenium 3.5 release to test again.

**Comment by jwhitlock** [comment]
Selenium 3.5 is released, with a new [Python selenium library](https://github.com/SeleniumHQ/selenium/tree/master/py) and [pytest plugin])(https://github.com/pytest-dev/pytest-selenium). The tracking issue https://github.com/SeleniumHQ/selenium/issues/3808 is closed. However, there are no 3.5.x images for [hub](https://hub.docker.com/r/selenium/hub/tags/) or [node-firefox](https://hub.docker.com/r/selenium/node-firefox/tags/) yet.

I've rebased and installed today's libraries, and the tests immediately fail in ``check_response``:

```
>       raise exception_class(message, screen, stacktrace)
E       WebDriverException: Message: None
E       Stacktrace:
E           at java.util.HashMap.putMapEntries (HashMap.java:500)
E           at java.util.HashMap.putAll (HashMap.java:784)
E           at org.openqa.selenium.remote.DesiredCapabilities.<init> (DesiredCapabilities.java:55)
...
```

Full output in https://gist.github.com/jwhitlock/167dc3ed2d0f8f654a9fe3f05cc4c924.

**Comment by jwhitlock** [comment]
New 3.5.0 images are released for [hub](https://hub.docker.com/r/selenium/hub/tags/) or [node-firefox](https://hub.docker.com/r/selenium/node-firefox/tags/). I've rebased on master and updated the script to use the new tags.  I'm also preparing the script to be used in the future, because I think it will be useful.

The nodes no longer fail with an exception, but instead run the tests. Progress! Unfortunately, our functional tests are broken ([bug 1394480](https://bugzilla.mozilla.org/show_bug.cgi?id=1394480)), so I can't see if they pass yet.  Working on that next.

**Comment by jwhitlock** [comment]
Rebase for working functional tests, plus updating requirements to latest and using the 3.5.3 docker image tags.

Short version:
* Chrome works when run in a node or directly
* Firefox fails many tests with timeouts when run in a node
* Firefox fails two tests when run directly, attempting to load GitHub or Bugzilla

``scripts/run_selenium_hub.sh`` runs the Chrome tests without errors. Firefox tests run, but fail.  The first failure is ``test_header_tech_submenu`` in ``test_article.py``, on ``page.header.show_tech_submenu()``, timing out waiting for the menu to be displayed:

```
tests/functional/test_article.py::test_header_tech_submenu FAILED

=================================== FAILURES ===================================
___________________________ test_header_tech_submenu ___________________________

base_url = 'https://developer.allizom.org'
selenium = <selenium.webdriver.remote.webdriver.WebDriver (session="643a8cad-1994-4f53-89c0-ae99c756cf91")>

    @pytest.mark.smoke
    @pytest.mark.nondestructive
    def test_header_tech_submenu(base_url, selenium):
        page = ArticlePage(selenium, base_url).open()
        assert page.header.is_tech_submenu_trigger_displayed
        assert not page.header.is_tech_submenu_displayed
>       page.header.show_tech_submenu()

tests/functional/test_article.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/pages/base.py:114: in show_tech_submenu
    self.wait.until(lambda s: submenu.is_displayed())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.support.wait.WebDriverWait (session="643a8cad-1994-4f53-89c0-ae99c756cf91")>
method = <function <lambda> at 0x7f6204327cf8>, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       TimeoutException: Message:

/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py:80: TimeoutException
```

Results are better when testing against Firefox 55.0.3 and geckodriver 0.19.0, with two failures:

```
============================================================= FAILURES ==============================================================
________________________________________________________ test_header_signin _________________________________________________________
Traceback (most recent call last):
  File "/Users/john/src/kuma/tests/functional/test_home.py", line 74, in test_header_signin
    assert 'https://github.com' in str(selenium.current_url)
AssertionError: assert 'https://github.com' in 'https://developer.allizom.org/en-US/'
 +  where 'https://developer.allizom.org/en-US/' = str('https://developer.allizom.org/en-US/')
 +    where 'https://developer.allizom.org/en-US/' = <selenium.webdriver.firefox.webdriver.WebDriver (session="0832b8ba-f39c-5c4f-93ce-72aef80543f8")>.current_url
---------------------------------------------------------- pytest-selenium ----------------------------------------------------------
URL: https://developer.allizom.org/en-US/
Driver log: /private/var/folders/61/s6_xxhqd3nl27_vgq9fzjmkr0000gq/T/pytest-of-john/pytest-4/test_header_signin1/driver.log
WARNING: Failed to gather log types: Message: GET /session/0832b8ba-f39c-5c4f-93ce-72aef80543f8/log/types did not match a known command
________________________________________________________ test_report_content ________________________________________________________
Traceback (most recent call last):
  File "/Users/john/src/kuma/tests/functional/test_report.py", line 21, in test_report_content
    selenium.switch_to_window(selenium.window_handles[1])
IndexError: list index out of range
---------------------------------------------------------- pytest-selenium ----------------------------------------------------------
URL: https://developer.allizom.org/en-US/docs/User:anonymous:uitest
Driver log: /private/var/folders/61/s6_xxhqd3nl27_vgq9fzjmkr0000gq/T/pytest-of-john/pytest-4/test_report_content0/driver.log
WARNING: Failed to gather log types: Message: GET /session/69b1ecab-6f08-fd4a-8820-4c28b45b101c/log/types did not match a known command
======================================================== 7 tests deselected =========================================================
================================== 2 failed, 35 passed, 75 skipped, 7 deselected in 191.61 seconds ==================================
============================================================= FAILURES ==============================================================
________________________________________________________ test_header_signin _________________________________________________________
Traceback (most recent call last):
  File "/Users/john/src/kuma/tests/functional/test_home.py", line 74, in test_header_signin
    assert 'https://github.com' in str(selenium.current_url)
AssertionError: assert 'https://github.com' in 'https://developer.allizom.org/en-US/'
 +  where 'https://developer.allizom.org/en-US/' = str('https://developer.allizom.org/en-US/')
 +    where 'https://developer.allizom.org/en-US/' = <selenium.webdriver.firefox.webdriver.WebDriver (session="0832b8ba-f39c-5c4f-93ce-72aef80543f8")>.current_url
---------------------------------------------------------- pytest-selenium ----------------------------------------------------------
URL: https://developer.allizom.org/en-US/
Driver log: /private/var/folders/61/s6_xxhqd3nl27_vgq9fzjmkr0000gq/T/pytest-of-john/pytest-4/test_header_signin1/driver.log
WARNING: Failed to gather log types: Message: GET /session/0832b8ba-f39c-5c4f-93ce-72aef80543f8/log/types did not match a known command
________________________________________________________ test_report_content ________________________________________________________
Traceback (most recent call last):
  File "/Users/john/src/kuma/tests/functional/test_report.py", line 21, in test_report_content
    selenium.switch_to_window(selenium.window_handles[1])
IndexError: list index out of range
---------------------------------------------------------- pytest-selenium ----------------------------------------------------------
URL: https://developer.allizom.org/en-US/docs/User:anonymous:uitest
Driver log: /private/var/folders/61/s6_xxhqd3nl27_vgq9fzjmkr0000gq/T/pytest-of-john/pytest-4/test_report_content0/driver.log
WARNING: Failed to gather log types: Message: GET /session/69b1ecab-6f08-fd4a-8820-4c28b45b101c/log/types did not match a known command
======================================================== 7 tests deselected =========================================================
================================== 2 failed, 35 passed, 75 skipped, 7 deselected in 191.61 seconds ==================================
```
It's possible that FF has trouble opening new windows or tabs.

When running locally, Chrome passes all tests.

**Comment by davehunt** [comment]
> It's possible that FF has trouble opening new windows or tabs.

I suspect you will need to add a wait for the new window to open. You may even need to switch to the new window to wait for the page to load, although it appears you're ony checking the URL so that might not be required. There's an [expected condition for a new window provided by the python package](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/support/expected_conditions.py#L369-L377), which might be useful.

Does the github sign-in also happen in a new window? If so, perhaps it's the same fix. If not, then I would expect the click to wait for the page to load from github, and this may be a bug in Marionette.

**Comment by jwhitlock** [comment]
``test_home.py::test_header_signin`` suceeded when I tried it today. The GitHub login page opens in the same tab, not a new one. Maybe it needs to wait a little longer to consistently pass, or maybe there was something else during the last test, like already being signed into GitHub.

``test_report.py::test_report_content`` failed again. Bugzilla opened in a new tab, and by the time the debugger opened, it was available as ``selenium.window_handles[1]``. Adding a wait for the second window to be available should work.

The [hub/node tests completed in Jenkins](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/21/), taking 11 hours to run, with 2 failures, 9 passing, and 27 errors. Search for ``FAILURES`` to see the test failures in the [console log](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/21/console).

**Comment by davehunt** [comment]
11 hours?!

**Comment by jwhitlock** [comment]
Yes, 11 hours. One of the lines is:

```
Resuming build at Wed Sep 20 07:18:07 UTC 2017 after Jenkins restart
```
I suspect the Jenkins restart caused a hang-up to become a failure or error, and the job would have never completed without it. I think a timeout is needed for future runs of this PR.

**Comment by davehunt** [comment]
I would recommend using the [build timeout](https://plugins.jenkins.io/build-timeout) plugin for stopping any build that exceeds your preferred timeout. In the past we also used the [pytest-timeout](https://pypi.python.org/pypi/pytest-timeout) plugin for timing out individual tests, but that doesn't work well when combined with the pytest-xdist plugin for running tests in parallel.

**Comment by jwhitlock** [comment]
I've opened #4441 to add some intentional waits (wait for a new tab to be available, wait for the URL to change) that makes the locally-run tests work in Firefox 55.

I've added that commit here, and [Jenkins is building it](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/).

@glogiotatidis, please take a look at does @davehunt's [message](https://github.com/mozilla/kuma/pull/4195#issuecomment-331372732) about the [build timeout plugin](https://plugins.jenkins.io/build-timeout). Does this fall under your Jenkins work, or should I take  on that task?

**Comment by glogiotatidis** [comment]
> @glogiotatidis, please take a look at does @davehunt's message about the build timeout plugin. Does this fall under your Jenkins work, or should I take on that task?

I installed the 'build-timeout' plugin on Jenkins for you (/cc @metadave). I'll integration to mdn pipeline to you.

**Comment by jwhitlock** [comment]
Thanks @glogiotatidis ! If it requires ``Jenkinsfile`` changes, please coordinate with me, because I'm rearranging stuff in PR #4444.

**Comment by jwhitlock** [comment]
Next round with the the 3.6.0 Selenium release:

* Works locally with Firefox 56.0 and Chrome 61
* Works with hub and Chrome node
* Fails with hub and Firefox node, during setup of first test, with the error ``WebDriverException: Message: Unable to find a matching set of capabilities``.  The capabilities are set as ``--capability browserName firefox``.

**Comment by davehunt** [comment]
> Fails with hub and Firefox node

Do you have details of the Firefox and geckodriver versions on the node? It sounds like the hub is not forwarding the new session request to the node. Could you provide the logs from the hub console?

**Comment by jwhitlock** [comment]
It's the [node-firefox](https://hub.docker.com/r/selenium/node-firefox/) Docker image, tag 3.6.0.  The output says Firefox 56.0, geckodriver 0.19.0.

* [Console log on Jenkins](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/23/consoleFull)
* [Logs from run_selenium_hub.sh](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c), including [logs from the hub](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c#file-output-20171006-txt-L315-L347) and [logs from the firefox node](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c#file-output-20171006-txt-L349-L379)

**Comment by jwhitlock** [comment]
Rebase on master, and then try some suggestions from the issue on mozilla/geckodriver:

1. Enable trace-level logging. This took some work, and https://github.com/SeleniumHQ/docker-selenium/pull/597. I could see no change in the logs.
2. Add ``--shm-size 2G``, to avoid an issue that causes Firefox to crash when run in docker. No effect.

**Comment by davehunt** [comment]
@jwhitlock I think this might be related to https://github.com/pytest-dev/pytest-selenium/issues/136. If you can try with the changes from https://github.com/pytest-dev/pytest-selenium/pull/137 that would be helpful. Thanks!

**Comment by jwhitlock** [comment]
@davehunt Tests are running again (directly and with Remote driver in hub/node) by updating to Selenium 3.7.1 docker images and py/selenium 3.7.0.

**Comment by davehunt** [comment]
@jwhitlock the issue hasn't been fixed yet, so you'd need to install pytest-selenium from the aforementioned branch. Hopefully I can release 1.11.2 tomorrow with the fix.

**Comment by jwhitlock** [comment]
Sorry, I'm having trouble getting that branch installed in my Docker image. Here's the current state:

With https://github.com/pytest-dev/pytest-selenium/pull/137

* Local run, Chrome 61, chromedriver 2.32 - *Good but flaky tests*
  - Run 1: 212 passed, 1 failed (``tests/functional/test_search.py::test_search_zero_results`` on ``wait_for_page_to_load``)
  - Run 2: 212 passed, 1 failed (``tests/functional/test_article.py::test_header_feedback_submenu`` on ``show_feedback_submenu``)
* Local run, Firefox 56.0.2, geckodriver 0.19.1 👍
  - Run 1: 213 passed
  - Run 2: 213 passed

With pytest-selenium 1.11.1 (current release):

* Local run, Chrome 62, chromedriver 2.33: 👍
  - Run 1: 213 passed
* Local run, Firefox 56.0.2, geckdriver 0.19.1 - *Good but flaky tests, server crying*
  - Run 1: 211 passed, 2 failed (``tests/functional/test_dashboard.py::test_dashboard``, ``is_first_details_diff_displayed``, and ``tests/headless/test_redirects.py::test_legacy_urls[url5]``, 504 status code)
  - Run 2: ``tests/headless/test_redirects.py::test_legacy_urls[url15]``, 504 status code)

I think the differences are due to server weather rather than https://github.com/pytest-dev/pytest-selenium/issues/136.

With ``scripts/run_selenium_hub.sh`` (just functional tests):
* Chrome
  - Run 1: 37 pass
  - Run 2: 37 pass
* Firefox
  - Run 1: 31 pass, 6 fail
  - Run 2: 31 pass, 6 fail
  - Failures:
     1. ``tests/functional/test_article.py::test_header_tech_submenu``, ``page.header.show_tech_submenu()``
    2. ``tests/functional/test_article.py::test_header_feedback_submenu``,
``page.header.show_feedback_submenu()``
    3. ``tests/functional/test_dashboard.py::test_dashboard``, ``page.is_first_details_diff_displayed``,
    4. ``tests/functional/test_home.py::test_header_tech_submenu``, ``page.header.show_tech_submenu()``
    5. ``tests/functional/test_report.py::test_report_content``, ``page.header.show_feedback_submenu()``
    6.  ``tests/functional/test_report.py::test_report_bug``, ``page.header.show_feedback_submenu()``

In [Jenkins](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/28/) (just Firefox): 30 pass, same 6 failed tests as ``scripts/run_selenium_hub.sh``

I'm considering:
1. Update dependencies and test in Jenkins on current Chrome 62 (current version), rather than Firefox 42 (oldest supported by Selenium 2.x)
2. Support Chrome or Firefox for local tests
3. Continue testing Firefox in Jenkins with new Selenium releases

**Comment by davehunt** [comment]
@jwhitlock pytest-selenium 1.11.2 is available now, which should help with the "Unable to find a matching set of capabilities" issue.

**Comment by jwhitlock** [comment]
The problem went away with me with Selenium 3.7.1 Docker images. I've updated to pytest-selenium 1.11.2, and I'm having some trouble with Chrome in Jenkins. It may just be server weather, or maybe I need to adjust those tests. There's lots of moving parts, and none of them are particularly reliable.

**Comment by jwhitlock** [comment]
First bit of progress in a while. I updated to the 3.8.1 Docker images, and had the same results as 3.7.1. I tried some interactive testing in pdb, and the ``--html`` output, and then guessed that there was an issue with ``move_to_element`` when running Firefox remotely, to emulate a mouse hover.

This was the hover code:

```python
            hover = ActionChains(self.selenium).move_to_element(submenu_trigger)
            hover.perform()
```

If I first move the mouse to just left of the submenu, and then onto the submenu, I can get the hover action to occur:

```python
            hover = (ActionChains(self.selenium)
                     .move_to_element_with_offset(submenu_trigger, -5, 0)
                     .move_to_element(submenu_trigger))
            hover.perform()
```

My guess is that, for the remote Firefox, there's no current mouse position. The first move teleports the cursor to the element, and doesn't give the browser a chance to register it as a hover. Moving to a outside point, and then onto the element, allows Firefox to register the element getting focus and activates the hover.  This trick isn't needed when running against Chrome or local Firefox, just when running against dockerized Firefox with the Remote driver.

I'll continue tomorrow and see if I can get the remaining tests working locally with similar tricks, and then take next steps toward working in Jenkins and a mergeable PR.

**Comment by jwhitlock** [comment]
I've gotten the integration tests running successfully with Selenium Grid (hub + chrome node + firefox node). I've opened a few PRs:

* PR #4592 - Update the functional tests either 1) work with Remote Firefox or 2) xfail for known issues
* PR #4593 - Switch integration tests to run Chrome, Firefox, and Headless in parallel, with many options to avoid failures from flakiness

I'll rebase when / if those are merged, and clean up.  That would leave:
* The tool updates (selenium 3 + pytest packages)
* The ``scripts/run_selenium_docker.sh`` script, to run tests against dockerized stand-alone browsers. I find this allows me to work on tests while doing other things with my computer, so I may keep it. This version is also better for interactive debugging.
* The ``scripts/run_selenium_hub.sh`` script, to run tests with dockerized hub / node browsers. This is a closer match to what runs in Jenkins, and can reproduce other errors. It may be more productive to use this rather than "commit and pray" development for Selenium errors.

I think I will try to get the scripts into a seperate PR as well, so that this becomes just the tool update.

**Comment by jwhitlock** [comment]
I merged the two scripts ``scripts/run_selenium_docker.sh`` and ``scripts/run_selenium_hub.sh`` into one horrible bash script that can also run against the development environment (almost). I've put that work into PR #4600.

I rearranged this PR to build on top of the other PRs. I'll wait for those to be merged, and then I should be able to reduce this to a one-commit PR.

**Comment by jwhitlock** [comment]
This pull request is ready! 🎉 

The functional test ``test_dashboard`` failed in Firefox when it ran the full test procedure, but when it was broken up into a series of tests, it passed locally and in [Jenkins](https://ci.us-west.moz.works/blue/organizations/jenkins/mdn_multibranch_pipeline/detail/upgrade_pytest_1308322/58/pipeline). 🤷‍♂️

There's an extra commit to allow the tests to run in Jenkins, and if I remove it, it will delete the test run in Jenkins. I can remove the commit before merging, or I can delete ``Jenkinsfiles/upgrade_pytest_1308322.yml`` in a new PR.

**Pull request merged**
