### PR TITLE
Add ratelimiting to homepage, document, and revision views

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by safwanrahman** [comment]
I think document list views also should be under ratelimitation.

**Comment by metadave** [comment]
can the values `400/m`, `40/m`, `20/m`, `15/m` be constants?

**Comment by jwhitlock** [comment]
I asked @jgmize not to make them constants. I find it challenging to understand what is going on when ``RATELIMIT_FOR_HOME`` is used, and ``RATELIMIT_40_REQUESTS_PER_MINUTE`` is worse than the literal string, because you have to go verify the value is what the name implies.

But, you are the second person to ask for a constant, so this may be a situation where I'm the holdout, and we should use the constant.

**Comment by metadave** [comment]
I wasn't thinking of constants like `RATELIMIT_40_REQUESTS_PER_MINUTE`, but rather have them grouped according to usage. ex: `RATELIMIT_HIGH = 400/m`, `RATELIMIT_LOW = 15/m`

**Pull request merged**
