### PR TITLE
bug 1294906 remove article titles from language dropdown

### PR DESCRIPTION
**Pull request by MatonAnthony**
bug 1294906 remove article titles from language dropdown

I tested it with a German page since Michael updated part of the list, but the updated list isn't complete yet.

I used a German page and I had a Spanish translation in my list, Spanish being one of the language already translated in German.

Thanks @koehlermichael ;)

### CODE REVIEW

**Comment by koehlermichael** [comment]
Theoretically the list is complete, practically the sync apparently was conducted while the translation was still in progress. Besides, I thought there should already be a list somewhere in a Mozilla project containing translated language names. Oh well.

**Comment by MatonAnthony** [comment]
Well, I got enough data to test my fix ;)

**Comment by safwanrahman** [comment]
r+ from my end

**Comment by koehlermichael** [comment]
It’s good to know one has one’s uses.

**Comment by safwanrahman** [comment]
@MatonAnthony Please remove (this line from test)[https://github.com/MatonAnthony/kuma/blob/c11d6a7cd56ebf6c31425b14c60665c8f1217cbb/kuma/wiki/tests/test_views.py#L2037] also remove the merge commit from your pull request.
Then it will ready to go

**Comment by jwhitlock** [comment]
I can squash the commits on merge. Assigning to @stephaniehobson.

**Comment by stephaniehobson** [comment]
:+1:

**Pull request merged**
